{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.4.jar",
          "size": 6098843,
          "sha512": "01d330df70c00efe2c10066e8ae238f445ac5edbf0a6a1f863dcb198336ca217e004188ac77f1380fadf4b3d07f903cbc50351e9827ed034d6a05f6c34bd8b21",
          "sha256": "b6fd5b20dd1a84c804856dc8141096cbdd4cc64d8690aa041f9374075e7805f5",
          "sha1": "20ca0ff99e863b101e91eae3aa0887f0671f9791",
          "md5": "8cb0e923b59c726048f825f4784fd4ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.4.jar",
          "size": 6098843,
          "sha512": "01d330df70c00efe2c10066e8ae238f445ac5edbf0a6a1f863dcb198336ca217e004188ac77f1380fadf4b3d07f903cbc50351e9827ed034d6a05f6c34bd8b21",
          "sha256": "b6fd5b20dd1a84c804856dc8141096cbdd4cc64d8690aa041f9374075e7805f5",
          "sha1": "20ca0ff99e863b101e91eae3aa0887f0671f9791",
          "md5": "8cb0e923b59c726048f825f4784fd4ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.4-sources.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.4-sources.jar",
          "size": 6076165,
          "sha512": "cba9c0a6dbf268e8f58d28b43b3500e43b48a7166fdd14b4f784fd547379e82e464a4d0763210a66680dcefe294ff035c4c52796b2cb1400d00645f66958ffd8",
          "sha256": "d54f87c083697d7d8f3367480f60c37d9b091e35b8e20ee8ec89e598083eb4f1",
          "sha1": "becee886a5508adf607ac1e8c13d3e15c6a1f067",
          "md5": "4f300e0164d3fb1ae7f08e9e1975e39f"
        }
      ]
    }
  ]
}
