{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.0+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.5.jar",
          "size": 6098844,
          "sha512": "d18d04719b11ab292b18c111344a019f732037caecaf9dbc45ab0485399729f3d04a3b549896e8d66696efd70bb8fcab66bb1fbbe34e58f03dac0073b30bc9c0",
          "sha256": "fa50144dccf430843ccd918320624666e2e00ec6b4b8401c0027b0545dac966e",
          "sha1": "95c7539a1ecf62b73862e34979ad269b8bbd3ccd",
          "md5": "3961d8113336b095994726d610e376e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.5.jar",
          "size": 6098844,
          "sha512": "d18d04719b11ab292b18c111344a019f732037caecaf9dbc45ab0485399729f3d04a3b549896e8d66696efd70bb8fcab66bb1fbbe34e58f03dac0073b30bc9c0",
          "sha256": "fa50144dccf430843ccd918320624666e2e00ec6b4b8401c0027b0545dac966e",
          "sha1": "95c7539a1ecf62b73862e34979ad269b8bbd3ccd",
          "md5": "3961d8113336b095994726d610e376e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.5-sources.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.5-sources.jar",
          "size": 6076165,
          "sha512": "cba9c0a6dbf268e8f58d28b43b3500e43b48a7166fdd14b4f784fd547379e82e464a4d0763210a66680dcefe294ff035c4c52796b2cb1400d00645f66958ffd8",
          "sha256": "d54f87c083697d7d8f3367480f60c37d9b091e35b8e20ee8ec89e598083eb4f1",
          "sha1": "becee886a5508adf607ac1e8c13d3e15c6a1f067",
          "md5": "4f300e0164d3fb1ae7f08e9e1975e39f"
        }
      ]
    }
  ]
}
