{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 78551,
          "sha512": "090142678b75808a1c26997e85e505908adc1202d28830480c0a06b1858c073d4d1568f1ccf8fa3c72cb50437e6ec397bd7cd4f55456f4bdfe9dd91904c5a86b",
          "sha256": "d1e5523b95f52dcf99fafb899c657a084a3200f0098152a7a3177b6e590b6ec1",
          "sha1": "a512b59e4b1682a4e2b5a3f7ae418f30ebf4af5c",
          "md5": "c06fcf81df21d5b3410d6699ebafdba0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.1+1.21.3"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 78551,
          "sha512": "090142678b75808a1c26997e85e505908adc1202d28830480c0a06b1858c073d4d1568f1ccf8fa3c72cb50437e6ec397bd7cd4f55456f4bdfe9dd91904c5a86b",
          "sha256": "d1e5523b95f52dcf99fafb899c657a084a3200f0098152a7a3177b6e590b6ec1",
          "sha1": "a512b59e4b1682a4e2b5a3f7ae418f30ebf4af5c",
          "md5": "c06fcf81df21d5b3410d6699ebafdba0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "size": 23049,
          "sha512": "10b302ed1b0679cf9277db777489694eaf1cb672d80c7ecb6abb8a7685fcd833a999eb7a20470adf570d72ed79754051e7ed6cedb7ca5bfecf787032bd021858",
          "sha256": "eacc2e792dc70de3a7ec742f5f7c8da5df4fe11fa094dc700927cd8ee43ebdb6",
          "sha1": "f6b41f047188be9ae49fc89f065b539bff80988f",
          "md5": "c82d8c77d8333ed7af41b20b973982a0"
        }
      ]
    }
  ]
}
