{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 6099261,
          "sha512": "cae0be2732cb633d6a3264781ef91fdb0859021eb49868f94d907e2746e8c3d512fff61ba8da01ef29f12b718dc912ef83727636ea76e63d7662ca1904feda83",
          "sha256": "62a6041a479c84d4b42510b8fdd1c63e9ed591dfebcfc785d07a5e4535157988",
          "sha1": "e32e55607e821d25f6855405f36fa05714c65759",
          "md5": "071ac874cab828be50f61892186dc7e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.1+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 6099261,
          "sha512": "cae0be2732cb633d6a3264781ef91fdb0859021eb49868f94d907e2746e8c3d512fff61ba8da01ef29f12b718dc912ef83727636ea76e63d7662ca1904feda83",
          "sha256": "62a6041a479c84d4b42510b8fdd1c63e9ed591dfebcfc785d07a5e4535157988",
          "sha1": "e32e55607e821d25f6855405f36fa05714c65759",
          "md5": "071ac874cab828be50f61892186dc7e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "size": 6076532,
          "sha512": "7f69ae6d68b721c59f8e79c266c3414ee1bda72e531443c18dacd711e05e6dab6775adb97cda8664ae9663cf521a866470e748d332863d49d244e765c2169220",
          "sha256": "019a59b9f025d201416ec185a923b5e1489e9a79eab93b9100acf69dd74407d0",
          "sha1": "5b5491727650bc4f451856bc93843e91bb12a91c",
          "md5": "11f5d81ffb3cb295de526e948905e2f7"
        }
      ]
    }
  ]
}
