{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 44917,
          "sha512": "f3653e05888ec220cb233ff24738a97123251da15498dd5adef36daf63f1601ef62dfca6c96fdd073ee5df373db2c384f41a6e539c0e6a8f16288b74a7038483",
          "sha256": "2e43b8fde803ec0f6423e3ddfb5e0f85cc832476993a6c7bee6af25c399d7e97",
          "sha1": "d814a29aaf2c039a5717df9015be36ccf3f9e5d2",
          "md5": "83cca8084e93f0bc4945546928f39220"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.1+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3.jar",
          "size": 44917,
          "sha512": "f3653e05888ec220cb233ff24738a97123251da15498dd5adef36daf63f1601ef62dfca6c96fdd073ee5df373db2c384f41a6e539c0e6a8f16288b74a7038483",
          "sha256": "2e43b8fde803ec0f6423e3ddfb5e0f85cc832476993a6c7bee6af25c399d7e97",
          "sha1": "d814a29aaf2c039a5717df9015be36ccf3f9e5d2",
          "md5": "83cca8084e93f0bc4945546928f39220"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.3-sources.jar",
          "size": 25374,
          "sha512": "d84f31a6d518675417c8f9edb0d0d1a09ca73859cb7e7193de65a4f151f72b3e51bcfc29810f66096835fb08abb301eea35ad71686c7786e0ecbf76aab6f0930",
          "sha256": "5d432a8f709c9495569957414e58cbc3d0e8dbf2a813396a3e400cb11888c24a",
          "sha1": "31a6951a8a7d1d8357ab542b6b7000a716981b05",
          "md5": "aeadf7d7f46328762ec9b76e4f30a71d"
        }
      ]
    }
  ]
}
