{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "size": 44553,
          "sha512": "73025811ad1ecdc0d9209ab5c9d01082018b974b6f8ca5d81d0fa7698604657d9b45c415f014d5a5f28164f28890673db423d163ea759a7d306fe2eda330e70b",
          "sha256": "d0b1d14916194dd041571619ab94b3139e5ce207a1029198308a5bda006a6086",
          "sha1": "e9fcb218642ca4ac82f9c93c920672e005d6fb74",
          "md5": "77c7a72063f5bdc01a44c60a85f251dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "size": 44553,
          "sha512": "73025811ad1ecdc0d9209ab5c9d01082018b974b6f8ca5d81d0fa7698604657d9b45c415f014d5a5f28164f28890673db423d163ea759a7d306fe2eda330e70b",
          "sha256": "d0b1d14916194dd041571619ab94b3139e5ce207a1029198308a5bda006a6086",
          "sha1": "e9fcb218642ca4ac82f9c93c920672e005d6fb74",
          "md5": "77c7a72063f5bdc01a44c60a85f251dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2-sources.jar",
          "size": 25201,
          "sha512": "aa9572228a018dc019adaf10555197df8a206b7cc157e6172632d9c12ff8b23663406547f6033250fcc327a84009c09dc133d1a809ce11124e759703ec5bd5c6",
          "sha256": "c3747e8136e8afef51a4f31328c4c8d708893efd0d5bdcf310edc0e58a71e1f4",
          "sha1": "01477c7eefe151d4c2c1b372b38b9cfdfa3636b4",
          "md5": "10465793b304933b6e87cc867e0ce591"
        }
      ]
    }
  ]
}
