{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "size": 78120,
          "sha512": "3ddb6be3340b08e8c35d5966207aec8d6f3c65327d5003af079e890704fdfc8f4da78b87b48db063d43d634cbbefaa7043b2660478f76eda62abfef9d0e6f590",
          "sha256": "6c4a231666d45c17a20796118fc9eb6172e89cebc62590f0d3c1af2c4d7cfe9e",
          "sha1": "45f3f5b9f324a63795b4c2d652f6970966816958",
          "md5": "55a597bf1f21b251ae24b24a1ea7784c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2.jar",
          "size": 78120,
          "sha512": "3ddb6be3340b08e8c35d5966207aec8d6f3c65327d5003af079e890704fdfc8f4da78b87b48db063d43d634cbbefaa7043b2660478f76eda62abfef9d0e6f590",
          "sha256": "6c4a231666d45c17a20796118fc9eb6172e89cebc62590f0d3c1af2c4d7cfe9e",
          "sha1": "45f3f5b9f324a63795b4c2d652f6970966816958",
          "md5": "55a597bf1f21b251ae24b24a1ea7784c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.2-sources.jar",
          "size": 22787,
          "sha512": "768c01bedf11b11a12ba0dfa0609d170031f4c7981ba092fee28c5be92e887500d5a95d2b16a1ac38c573c7a6d288c07a8ddc68fe1ce5b7f71fba0b08134778e",
          "sha256": "97e2f23ba454f92963d13bd650b2bc8526d63966ddde7885586091b7ceb3a93a",
          "sha1": "51f5989e050d72de7ab970fd80b178aa450eaba1",
          "md5": "d8f873f0988ae3cf0975a8f2d533a658"
        }
      ]
    }
  ]
}
