{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.2.jar",
          "size": 86749,
          "sha512": "92cb988b1525128b31fb7ca7a0d1ef5c534ec768217b9f55abdf9b8bbbdbd6348ec66077781cd2faed8d35911faf519a181fb3aa5a7e845f873f92b967081adb",
          "sha256": "d98f23179babb65dd4b2c81b7ec83e8c358b7231880e7cec651a202761fd9f1a",
          "sha1": "de903607a9f5fd845a223c98caa4cc6ce80722ec",
          "md5": "cee43ffc364538b04ec263c713ea4bb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.2.jar",
          "size": 86749,
          "sha512": "92cb988b1525128b31fb7ca7a0d1ef5c534ec768217b9f55abdf9b8bbbdbd6348ec66077781cd2faed8d35911faf519a181fb3aa5a7e845f873f92b967081adb",
          "sha256": "d98f23179babb65dd4b2c81b7ec83e8c358b7231880e7cec651a202761fd9f1a",
          "sha1": "de903607a9f5fd845a223c98caa4cc6ce80722ec",
          "md5": "cee43ffc364538b04ec263c713ea4bb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.2-sources.jar",
          "size": 22834,
          "sha512": "96ff4641ac4ac46a8c423cb985a0ad85cd9ba52f38e8d1eeb9061a6da07636aa4f71a2a2acdec490c47ccb035f9fda206946e577048a9bf220466e9a7b1f0478",
          "sha256": "a03950d0e73a2ab0951e246f82bdf0eb7d9c005f42796a97fee878c7e3aad5b8",
          "sha1": "f8865e435f9872738bd73efdcf0e489a3e8a9bb4",
          "md5": "9b08cfb5067c6ec3df0e252a532131f0"
        }
      ]
    }
  ]
}
