{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 6098292,
          "sha512": "59db1545211aaecdddc5838c150072abdd744fd0bef98936676ddc8acc5a529c978d03066fd2b480040c2cbd9705f9e1a418258d76acb0cf484fd305ea6c228f",
          "sha256": "10182406a0324adc6b139ab16be9e245bff0aeffff8d153bb0c2f249cd0f44f0",
          "sha1": "cdad03a4f1676ec027729296f117e62e88a82781",
          "md5": "f2095dc5dd0f6e7b6011970928d80751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 6098292,
          "sha512": "59db1545211aaecdddc5838c150072abdd744fd0bef98936676ddc8acc5a529c978d03066fd2b480040c2cbd9705f9e1a418258d76acb0cf484fd305ea6c228f",
          "sha256": "10182406a0324adc6b139ab16be9e245bff0aeffff8d153bb0c2f249cd0f44f0",
          "sha1": "cdad03a4f1676ec027729296f117e62e88a82781",
          "md5": "f2095dc5dd0f6e7b6011970928d80751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "size": 6076161,
          "sha512": "138ee707c3fe0144c464cb762006e948e1bb5c7148f57ca30dcccae23579bdda5c190a17ca03c02f0aa1f8778ce097a6ef3dcaac05935ac1985f8bdf7a9f04dc",
          "sha256": "2c86679d2d1a05f6790c227eee273425fe0f322827f5fa9ff742df8cfc68920a",
          "sha1": "b232aa5b2790c39c70a0587461791285050c70e0",
          "md5": "a9540d40e0cb073e88444805de2ef987"
        }
      ]
    }
  ]
}
