{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 44004,
          "sha512": "c91ebc5505156141da493f7113219f8fd7a7bd487631572fa2dce91136738d0a31d0f2774f07e634db2b86846f1731cc105de2922769ddd41e6c82d3187eaf4c",
          "sha256": "e1b37c88e8c94f582823c1a4fb3358d7d992644e581577af03c1840b47390dc7",
          "sha1": "78c027831084b206a0cd4719817c5899bd729ea1",
          "md5": "19768209ee2549d31d7425e42dd04170"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 44004,
          "sha512": "c91ebc5505156141da493f7113219f8fd7a7bd487631572fa2dce91136738d0a31d0f2774f07e634db2b86846f1731cc105de2922769ddd41e6c82d3187eaf4c",
          "sha256": "e1b37c88e8c94f582823c1a4fb3358d7d992644e581577af03c1840b47390dc7",
          "sha1": "78c027831084b206a0cd4719817c5899bd729ea1",
          "md5": "19768209ee2549d31d7425e42dd04170"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "size": 25199,
          "sha512": "7987c2c34519e4ed71417702b3265570d537d18ac36b073cbb547b2233966a13be6b9f30d764abd51429b5091192ffa6eb2696e704f7343c3ab93ac0478e84e4",
          "sha256": "aec60688e687d6baa0515a02769167150f9d05f525b76cf016ba23453e370440",
          "sha1": "d284fe43631c5df1d09ef9c9bf64682fbf344ccf",
          "md5": "3c87a07b1543fd9ceeb817439da3181e"
        }
      ]
    }
  ]
}
