{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 78290,
          "sha512": "a93ac057871de68a97a75e6e1fdce66dd4fbf79e3b89d248161ee692e1564f5fc17cca70a4c5a98ec186d30aba3f118cc4e0eb8ad7b831e76a85be8f9120b935",
          "sha256": "3fa2d8bb182bef1623666c58cdca94886de0107bfa027fdb4d251da14713866a",
          "sha1": "c1ec1111be9e9330805540ad04b5be9076bc8084",
          "md5": "33d95e606902d3bed24c4447a42507a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8.jar",
          "size": 78290,
          "sha512": "a93ac057871de68a97a75e6e1fdce66dd4fbf79e3b89d248161ee692e1564f5fc17cca70a4c5a98ec186d30aba3f118cc4e0eb8ad7b831e76a85be8f9120b935",
          "sha256": "3fa2d8bb182bef1623666c58cdca94886de0107bfa027fdb4d251da14713866a",
          "sha1": "c1ec1111be9e9330805540ad04b5be9076bc8084",
          "md5": "33d95e606902d3bed24c4447a42507a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.8-sources.jar",
          "size": 22789,
          "sha512": "a52c17c1a3d892586891608f836fa3e7ce5c334c51511bb73863297cf4f42ef1d5d3d5bc88f0c5d5453bb9fd453d32f186615a525ba731dd9825f677cb3d63ce",
          "sha256": "9261a855ad1f1b71f75e280e33c3a247be429f43c2f05bb8dbe14238dc441d35",
          "sha1": "9402bbe96373f7133c58be29c66df74a35168032",
          "md5": "bf996d062914bf8d68a64482ac62188b"
        }
      ]
    }
  ]
}
