{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.jar",
          "size": 86521,
          "sha512": "bbaab7c68c0304734bf7e7eb26e892f352093d845fa64298325564e7eecc46312d7aa590368de1877b07a633cf5cb41b35140c990dd4c1a9562a418ed30b8d0a",
          "sha256": "77aff6cda57cea24399a789dae1cae1b344fc3c1d8a4ddced58e8351c096023a",
          "sha1": "c25bb11c897a698f7f26d878e663e8e5720178a5",
          "md5": "fb8e4ee05ea7e29ab31cdd987934e615"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.jar",
          "size": 86521,
          "sha512": "bbaab7c68c0304734bf7e7eb26e892f352093d845fa64298325564e7eecc46312d7aa590368de1877b07a633cf5cb41b35140c990dd4c1a9562a418ed30b8d0a",
          "sha256": "77aff6cda57cea24399a789dae1cae1b344fc3c1d8a4ddced58e8351c096023a",
          "sha1": "c25bb11c897a698f7f26d878e663e8e5720178a5",
          "md5": "fb8e4ee05ea7e29ab31cdd987934e615"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1-sources.jar",
          "size": 22805,
          "sha512": "177e11f72f17e8e84efa54308b940d09bfac53804e6a4046ac08c1cb5ab663bb1c028163f3e85acc32614d3f577d56e4ea9973bfb128f0cda028c281fde5b06b",
          "sha256": "30dfeaad7e78dd010c43a513378ccc8bf9171a4102acb16211ace5a477edec23",
          "sha1": "051bf479c9ee39e1f8b25002af10779639e05610",
          "md5": "c020271b958f9639fc85cbf5e01a5199"
        }
      ]
    }
  ]
}
