{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.jar",
          "size": 49918,
          "sha512": "baf6d36054b5de20fc1ccba767effd3e822183a69a7a1cd187ed4bfdf94c6ffbc5b001db25cd0829bec16253f7060546cbc0ce9dd673b4e488df790a399f3aa3",
          "sha256": "f7c02b909da5c811bc8793baba02af8d73c0fc2ee59e31590dc18246b7dc65da",
          "sha1": "e857888aeed8eb30189f16f46da0e53551578b14",
          "md5": "fceac83055fc3c4e1abb1c16687bf22a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.jar",
          "size": 49918,
          "sha512": "baf6d36054b5de20fc1ccba767effd3e822183a69a7a1cd187ed4bfdf94c6ffbc5b001db25cd0829bec16253f7060546cbc0ce9dd673b4e488df790a399f3aa3",
          "sha256": "f7c02b909da5c811bc8793baba02af8d73c0fc2ee59e31590dc18246b7dc65da",
          "sha1": "e857888aeed8eb30189f16f46da0e53551578b14",
          "md5": "fceac83055fc3c4e1abb1c16687bf22a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1-sources.jar",
          "size": 25199,
          "sha512": "b592297537eb8592d06b89d1300f9e1d9a3b148fb0822dc450b53935a7b4dcea0ef15c4256a030fba5d330e1330b5c1dda598d4ca1341a50283ff8042b31b813",
          "sha256": "bfe5c9c4dcedc09a19a59ec93181567425733bf6b21439dec53ac19919e5b9a4",
          "sha1": "07212404e1edb5aa00f539da8a3f304b846604a7",
          "md5": "6eb124183235ca867942479605150ae4"
        }
      ]
    }
  ]
}
