{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5.jar",
          "size": 44921,
          "sha512": "d19d21dafaf04de9eee4ca37e2247e44fe5cb704c1e87440170b8004782b78052c45591f0f36970ed5a0b7f78b6d371748a2c9fe348d7542b277be43cc9959a6",
          "sha256": "c3c0abb3a60a4209f17b18c3899c7913afe0b8b34064a20d803cd93557f9758a",
          "sha1": "56734e65d590115276662e432253659f766be0f4",
          "md5": "96a17d45208c2027975949a91543267b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.128.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5.jar",
          "size": 44921,
          "sha512": "d19d21dafaf04de9eee4ca37e2247e44fe5cb704c1e87440170b8004782b78052c45591f0f36970ed5a0b7f78b6d371748a2c9fe348d7542b277be43cc9959a6",
          "sha256": "c3c0abb3a60a4209f17b18c3899c7913afe0b8b34064a20d803cd93557f9758a",
          "sha1": "56734e65d590115276662e432253659f766be0f4",
          "md5": "96a17d45208c2027975949a91543267b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5-sources.jar",
          "size": 25379,
          "sha512": "bcc1caafae5ffdf7ca318dcbd970517895a852275c16e68ba9ed9e24a471e0c4a22df625d82737f390c09adab6d3f4239ddcb450eab6fec98477a24a15cc48dc",
          "sha256": "69d9a8ca0823d54f8a92d5678e0b59980fc89b24a6b621af785970901baf9129",
          "sha1": "31b12b1c5ecb6f789aaa13e072767c1608bcce1f",
          "md5": "b59aa84bae762bd73cf4c3293679fc9f"
        }
      ]
    }
  ]
}
