{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5.jar",
          "size": 78461,
          "sha512": "bff725dd19696dec32355608929977c0c4d442b6096bdb7bc26628ddfadd85585544bda691ed5f9ede88d3bc963167772a47ae3a6a9d95836f14423372d633be",
          "sha256": "10220161fadf5673dcd07076517c98ff8d8b54fb703a1b8881418d5940861cb0",
          "sha1": "0e7302cb7c4079ee13bcb4abde30ab473f84d50e",
          "md5": "330f188467010e0f6862cb1307747533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.128.2+1.21.5"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5.jar",
          "size": 78461,
          "sha512": "bff725dd19696dec32355608929977c0c4d442b6096bdb7bc26628ddfadd85585544bda691ed5f9ede88d3bc963167772a47ae3a6a9d95836f14423372d633be",
          "sha256": "10220161fadf5673dcd07076517c98ff8d8b54fb703a1b8881418d5940861cb0",
          "sha1": "0e7302cb7c4079ee13bcb4abde30ab473f84d50e",
          "md5": "330f188467010e0f6862cb1307747533"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.5-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.5-sources.jar",
          "size": 23050,
          "sha512": "e1afa25103abc72557c519502de39d55074fd947187a2e801bbb17bd227d93feabdf74e4ebc7e11c69206881a454b0e62349110cca648e2d1023fd39cee4ce60",
          "sha256": "1cc01ca605bfd1f97a14c0e2e7207798efb0c7fb8a51797d67695e019221768a",
          "sha1": "0afd5e3789dadd5c020324095a9464df3e1177a7",
          "md5": "1bb2843edd09f0b693b688a49ac7c14e"
        }
      ]
    }
  ]
}
