{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1.jar",
          "url": "rosetta-neoforge-0.1.0+26.1.jar",
          "size": 6098512,
          "sha512": "f18298a5b4b3cc2dc32a2ad78049497258a30eaa4e2e82199daa8729c5a705f7cbfca4bfe88a8e442024ec129b80db3962a06cb429676a5d5cf2ec5ef13f1b01",
          "sha256": "575a3526fe6ff7bd00cbb742cec8bb05bba8f9d92778267bc1b7c3fac5eb2c2e",
          "sha1": "32d6068c0013878da2cc1c62b3eb3fd4352f2048",
          "md5": "88c26de21e2e148cbad233c540ed6fee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1.jar",
          "url": "rosetta-neoforge-0.1.0+26.1.jar",
          "size": 6098512,
          "sha512": "f18298a5b4b3cc2dc32a2ad78049497258a30eaa4e2e82199daa8729c5a705f7cbfca4bfe88a8e442024ec129b80db3962a06cb429676a5d5cf2ec5ef13f1b01",
          "sha256": "575a3526fe6ff7bd00cbb742cec8bb05bba8f9d92778267bc1b7c3fac5eb2c2e",
          "sha1": "32d6068c0013878da2cc1c62b3eb3fd4352f2048",
          "md5": "88c26de21e2e148cbad233c540ed6fee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1-sources.jar",
          "url": "rosetta-neoforge-0.1.0+26.1-sources.jar",
          "size": 6076177,
          "sha512": "1ab359fe11ad91af70606a347774ca96efc9bb83e319a9da4402bc60d290a90a58f88d8827cce1fae57ff881dc3eebfbdb6af1304fd8f67533342bc47df379e7",
          "sha256": "e9bdc0a80f34a74bc15cb0fe2b20e38665704b78b9e0f5b753a04607de8890e4",
          "sha1": "fa9c928ed73785874fc8c5e8b8a9fc910f205285",
          "md5": "b4881024c5a1ed9fe9b907cbb47c3eed"
        }
      ]
    }
  ]
}
