{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.1.jar",
          "url": "rosetta-fabric-0.1.0+1.21.1.jar",
          "size": 6098763,
          "sha512": "ad3c2a5c557f521990c93527bf9ec51c7aa00888458025e7275750fdae7215e42ce65d964f2cf407f1d24ededa235e6b28ee400bf1ee5f5c3ed6fef30513187b",
          "sha256": "0cf8b28da7bc8a87af41adcc331cff405bf2464dad3bc1dac8d621abac776000",
          "sha1": "d652c1b18f320c7336b22b253fe4af097b148bb5",
          "md5": "4bd0bbb122fac80441806fccb539fb71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.4+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.1.jar",
          "url": "rosetta-fabric-0.1.0+1.21.1.jar",
          "size": 6098763,
          "sha512": "ad3c2a5c557f521990c93527bf9ec51c7aa00888458025e7275750fdae7215e42ce65d964f2cf407f1d24ededa235e6b28ee400bf1ee5f5c3ed6fef30513187b",
          "sha256": "0cf8b28da7bc8a87af41adcc331cff405bf2464dad3bc1dac8d621abac776000",
          "sha1": "d652c1b18f320c7336b22b253fe4af097b148bb5",
          "md5": "4bd0bbb122fac80441806fccb539fb71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.1-sources.jar",
          "url": "rosetta-fabric-0.1.0+1.21.1-sources.jar",
          "size": 6076546,
          "sha512": "e9c51d608625d69e7c979a5abaf77e19cd14e0dbc29807393cd3a13ebfb7b666e953419aaee696c9b53b373844ff43be18ffb6c7842a7804b6dead300adf2abe",
          "sha256": "22775dc7b82a43475aa97ef9ff53f7bf9385ad3405827bb167e0b3553627740c",
          "sha1": "ac542f74b0f9b6c8fd2cc67a17df9e47a3095a0b",
          "md5": "7cdba51bc9df7c4d6c45af5563fcfddf"
        }
      ]
    }
  ]
}
