{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8.jar",
          "size": 44405,
          "sha512": "f17e2e73a6135bb1dda0460b81d04853d529bcf4811540b17dc10294cd887ea824f1bddafa075e33e8b006493f20a76df91dbb50c312cd70e9489fa0ac12f178",
          "sha256": "b8feb5c5faab2cc6f747d91ed53bb6210be56a4d13f726c8b0bbadbac0447343",
          "sha1": "97aa35464495d8e7e8321e973111a8025c376a22",
          "md5": "ffbeab82ff43e21db9d635d81bf420f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.130.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8.jar",
          "size": 44405,
          "sha512": "f17e2e73a6135bb1dda0460b81d04853d529bcf4811540b17dc10294cd887ea824f1bddafa075e33e8b006493f20a76df91dbb50c312cd70e9489fa0ac12f178",
          "sha256": "b8feb5c5faab2cc6f747d91ed53bb6210be56a4d13f726c8b0bbadbac0447343",
          "sha1": "97aa35464495d8e7e8321e973111a8025c376a22",
          "md5": "ffbeab82ff43e21db9d635d81bf420f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8-sources.jar",
          "size": 25381,
          "sha512": "cac7c6ad0fc4728753acc9e8538f8fe7af97d212987915facc350666b7c13e71f658e2d5891a5fa548516ce7f468c469645eb1aa372091138e26d9029cb1bf0f",
          "sha256": "940140b4e4b0d843b9313d1b82d116c4bc4821298aa6f6efde3ccbdc146190f3",
          "sha1": "9601e0e6d2321e7d4376ef1a448fef701aff1b38",
          "md5": "29e419587fda95631cf1d1eadbf30962"
        }
      ]
    }
  ]
}
