{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8.jar",
          "size": 78705,
          "sha512": "2781b355bb1a09daf3e1b75d19db38ff3f09ab639fb557974ef5e37939b6bd390e6e83c3987197cffba5bdcf37bb74d7b8b7de8f913eaaa5356d70c754fdf46c",
          "sha256": "de89adf0d648340bed055ad935d567462e6bec8e44c64df2d36a86dc520afa31",
          "sha1": "d2eea2772711f9bbc860b40de0bb5a1a111450fa",
          "md5": "c3767ee12c5bb49639b21ea62dab660a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.130.0+1.21.8"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8.jar",
          "size": 78705,
          "sha512": "2781b355bb1a09daf3e1b75d19db38ff3f09ab639fb557974ef5e37939b6bd390e6e83c3987197cffba5bdcf37bb74d7b8b7de8f913eaaa5356d70c754fdf46c",
          "sha256": "de89adf0d648340bed055ad935d567462e6bec8e44c64df2d36a86dc520afa31",
          "sha1": "d2eea2772711f9bbc860b40de0bb5a1a111450fa",
          "md5": "c3767ee12c5bb49639b21ea62dab660a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.8-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.8-sources.jar",
          "size": 23049,
          "sha512": "827475f7e9e7a4b87778ee3d358a8d37350993eb9821269ca516844bb2bb79218ce8f1e7b3af0589808046d05f30ac1f3251b9543523b72720873c349417bc0e",
          "sha256": "ecd115faac3c02b19906c6654e68587bef99fbe3097e511b311edb5e67da92b5",
          "sha1": "f41f7f44c770eb42cb9d6fe6bce306236d3b55e1",
          "md5": "c6147612687d8e8bfff27464d6280f81"
        }
      ]
    }
  ]
}
