{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.11.jar",
          "size": 6098453,
          "sha512": "b77b8d05f084f80abe1680d931ed740d16110bf4b4edd6f7a9aed7ff32337a8f3c3d46384bb6d02c397a8cc764c47eac5b39e6b2c12ccbcc1daeb784cf0a1f45",
          "sha256": "3345a64f0e2d06763d52223ad9b41dbac521f1cb46e00d2c088bca618d183dcf",
          "sha1": "1f4920f6a7580fdb20d5db14ebb411f8c6b6ffa9",
          "md5": "a4fe4fd7a5667de2af0cf614b9a32613"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.11.jar",
          "size": 6098453,
          "sha512": "b77b8d05f084f80abe1680d931ed740d16110bf4b4edd6f7a9aed7ff32337a8f3c3d46384bb6d02c397a8cc764c47eac5b39e6b2c12ccbcc1daeb784cf0a1f45",
          "sha256": "3345a64f0e2d06763d52223ad9b41dbac521f1cb46e00d2c088bca618d183dcf",
          "sha1": "1f4920f6a7580fdb20d5db14ebb411f8c6b6ffa9",
          "md5": "a4fe4fd7a5667de2af0cf614b9a32613"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+1.21.11-sources.jar",
          "url": "rosetta-neoforge-0.1.0+1.21.11-sources.jar",
          "size": 6076110,
          "sha512": "9d4a3a5c0109f8f93b3c00d80299557c47f4d9febfdb82e261b18d4bca8afb5579404caa750c67240e2e37e2ef2b0fda7aa1ef700b278738895a3c99eb1f27f2",
          "sha256": "e8b16bc224e72de9f0f32b6331913b7849a34783b9c82e7dcfbc46ff9e00bcf3",
          "sha1": "acf5e6646bd3e5c7f43331a94af2d7d94ddfc4d8",
          "md5": "29232f97d1d3006eff795da11683f16b"
        }
      ]
    }
  ]
}
