{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "size": 49921,
          "sha512": "bb255a21e5d9d973c942fcff8817683223b9db0cd1d09fe0bfaac802b2eeb259a38b89fe70285cbaca74ddaf652f693fc2b29082872abcfaab5497f7864cc090",
          "sha256": "627df2b5ef6b03d7537e5472f693d54d929a34efab54af555230bb9bbe4773c5",
          "sha1": "27d458c786cd02e9304ef94c7b7d1f40f2d8a553",
          "md5": "a1e93d1f9120d2df22028e6f08cf73a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "size": 49921,
          "sha512": "bb255a21e5d9d973c942fcff8817683223b9db0cd1d09fe0bfaac802b2eeb259a38b89fe70285cbaca74ddaf652f693fc2b29082872abcfaab5497f7864cc090",
          "sha256": "627df2b5ef6b03d7537e5472f693d54d929a34efab54af555230bb9bbe4773c5",
          "sha1": "27d458c786cd02e9304ef94c7b7d1f40f2d8a553",
          "md5": "a1e93d1f9120d2df22028e6f08cf73a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1-sources.jar",
          "size": 25201,
          "sha512": "7306385074103392adb3840783a22ab25f1f5a5b1b20d4b1e52812263118e25dcf4fa186c0839ecf376d1fab8446d0925bcc32e1625bde1fd4ecf61c5ad0df36",
          "sha256": "ea3719ca2cfc814502166d73f4b1a71a55f49b017a4bf51418d3f6260933acc3",
          "sha1": "5ad39ff047bf201e11b18da4ec16e99e489cf250",
          "md5": "74a88f2b02143dd9e4e62dbc25ca12d6"
        }
      ]
    }
  ]
}
