{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "size": 86538,
          "sha512": "8943a2fe2eb08f9ff40459648357c17ef054de9f55567fafbbd967cfb35ea7ae51a603715f7e26adf542d5daf9b43fc6e404c9b3be5654ab1e48b74c321b2d1b",
          "sha256": "102ffd3f89db80d0bf5dc567f50ef9f8c71dd98ae667f9ac4b87984e685b96de",
          "sha1": "8be4670b30727b14887f85cacec4d0dac7a6a21a",
          "md5": "abdd9c3ba29c395de17d3e2cf96dc934"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+26.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1.jar",
          "size": 86538,
          "sha512": "8943a2fe2eb08f9ff40459648357c17ef054de9f55567fafbbd967cfb35ea7ae51a603715f7e26adf542d5daf9b43fc6e404c9b3be5654ab1e48b74c321b2d1b",
          "sha256": "102ffd3f89db80d0bf5dc567f50ef9f8c71dd98ae667f9ac4b87984e685b96de",
          "sha1": "8be4670b30727b14887f85cacec4d0dac7a6a21a",
          "md5": "abdd9c3ba29c395de17d3e2cf96dc934"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.1-sources.jar",
          "size": 22807,
          "sha512": "d76f44f29e3fb83fa1eaa671f5d71ab443cb15b32ae93a3e0297462477486eb66c882e14e5d073c526a5602064954ecc3e2b227f30d33898f5f7acec6f97d26e",
          "sha256": "5b7c3735d2161a84c7db5557d5b340c4eacdda758e56e678cc6becd0c44fd924",
          "sha1": "ada443505f992097ef35a44adecd07a9a8d2eb1f",
          "md5": "24c0d1121d17273c2327dbb347bd3918"
        }
      ]
    }
  ]
}
