{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2.jar",
          "size": 79124,
          "sha512": "f950d07ce5d425884da8384dd5eff7c9759108a405320e2f770d962557eab6cec69d6728813bdff7bd101b91b9bf6b1adc80286573ecc7df5be5179b531e93a2",
          "sha256": "c3b7f9244ad6271d1de5bd9f2aa1f5984fad8bd894d78986e8b3f376e1faf7e0",
          "sha1": "8ec7f2a212db386ea9f03149cb8c88784ba2442a",
          "md5": "e3a048613f4e43f827b38e07470a48c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.146.0+26.1.2"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2.jar",
          "size": 79124,
          "sha512": "f950d07ce5d425884da8384dd5eff7c9759108a405320e2f770d962557eab6cec69d6728813bdff7bd101b91b9bf6b1adc80286573ecc7df5be5179b531e93a2",
          "sha256": "c3b7f9244ad6271d1de5bd9f2aa1f5984fad8bd894d78986e8b3f376e1faf7e0",
          "sha1": "8ec7f2a212db386ea9f03149cb8c88784ba2442a",
          "md5": "e3a048613f4e43f827b38e07470a48c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2-sources.jar",
          "size": 22818,
          "sha512": "a356962cef72c91f4c833872c2da73a77677c06c9ec0d2dc5cc6a7b818820acb4925ee03b83daa417d93d53d91d39c040fe38b433489db96bcf7ae3c9b15b479",
          "sha256": "9ea381a4dd937aa110dedc8f3762291906a74f91369bdd4388c5c19baac59b1a",
          "sha1": "3ec9ccc40076fad6408bc38eda31164716fe3bba",
          "md5": "92940ce7b2fc18ca027591a9343625c7"
        }
      ]
    }
  ]
}
