{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2.jar",
          "size": 44428,
          "sha512": "034b09d90eafe941415fe0b58f306f2fcf16f192ae122efd21f28fc7c37b3737a4ac96cccd447d6c3c075b09f8c30a773ef928fb56ea32db222b588b766743ce",
          "sha256": "7a786aa43d743dc62359a47746e005c37ebdf7a3f5979c7732f4892d3988f053",
          "sha1": "f1a41b096dd2ca22f54c1fd10911cbe15c619894",
          "md5": "f4c45d7f8fc34a46e07aaddda60a014d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.146.0+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2.jar",
          "size": 44428,
          "sha512": "034b09d90eafe941415fe0b58f306f2fcf16f192ae122efd21f28fc7c37b3737a4ac96cccd447d6c3c075b09f8c30a773ef928fb56ea32db222b588b766743ce",
          "sha256": "7a786aa43d743dc62359a47746e005c37ebdf7a3f5979c7732f4892d3988f053",
          "sha1": "f1a41b096dd2ca22f54c1fd10911cbe15c619894",
          "md5": "f4c45d7f8fc34a46e07aaddda60a014d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.2-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1.2-sources.jar",
          "size": 25205,
          "sha512": "2bf8726a64d4846da2c175803e264dd908edeca347bdcbf18b360f5ac774a34ba1cc71de844e9d6265fdc0ba57df5cc25e39def5a25d32ca8f74c80ad24a81a9",
          "sha256": "41e7659cadd379446602fc95242ff3c0cf45dc1e7199933f86d2fafb675d9cdb",
          "sha1": "9ac36c4c5d0aef8107741cc561195e820177c317",
          "md5": "0e201fe4d37020a9180382c1dcc6090e"
        }
      ]
    }
  ]
}
