{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "size": 44556,
          "sha512": "495861f3dd013d2d26d4252a365e6fc8d4a5a58ebd6b5748172b70271207eb6d3c62232ca49a1f6e8d119a7019b30d5d06ea98bb43880eb180862f8ebebd78ad",
          "sha256": "381abfc29f4aefef3670cfdd72bea5cf29d09dc4b899d7240f00e2923ef307ef",
          "sha1": "6b811aba9cdf21652913aa659682b8b3982774c8",
          "md5": "938b0e91feea6a47e433638da6f4e732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "size": 44556,
          "sha512": "495861f3dd013d2d26d4252a365e6fc8d4a5a58ebd6b5748172b70271207eb6d3c62232ca49a1f6e8d119a7019b30d5d06ea98bb43880eb180862f8ebebd78ad",
          "sha256": "381abfc29f4aefef3670cfdd72bea5cf29d09dc4b899d7240f00e2923ef307ef",
          "sha1": "6b811aba9cdf21652913aa659682b8b3982774c8",
          "md5": "938b0e91feea6a47e433638da6f4e732"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4-sources.jar",
          "size": 25203,
          "sha512": "97c1df4076cded58da0f2f50a5c2c66ee77a716787b59d0eb4cbf12215ffaa83bc8b7e6c1c8f28425d164b25d6a9b163c477ccfc1ac39f039b408608db620220",
          "sha256": "63b0368752e92b8b6f8fafdbba849142d6a42c36d7e860d760cf123f9f8db867",
          "sha1": "bea8abcfbfda25b30fddca3f7a3dc427e96dc2bf",
          "md5": "6e44c7cea66e2eac68566827d75210aa"
        }
      ]
    }
  ]
}
