{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "size": 79324,
          "sha512": "16ef1c3f323fed4c69fd4e1694098bdfca5bb508519c11ea9dcad36896f261313bb71ac626cfbffd66d492f9d768fa763dd5e3b071fc8d8fb395e3afdb6522dd",
          "sha256": "907b8b37ffe4f137e928e40a55ae1ab4882bf27cbe145092999fe0074738732a",
          "sha1": "97e20d89334bd679b97521cb5e24ccefdd835598",
          "md5": "052d6e76291056dea05a185e059ed6ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4.jar",
          "size": 79324,
          "sha512": "16ef1c3f323fed4c69fd4e1694098bdfca5bb508519c11ea9dcad36896f261313bb71ac626cfbffd66d492f9d768fa763dd5e3b071fc8d8fb395e3afdb6522dd",
          "sha256": "907b8b37ffe4f137e928e40a55ae1ab4882bf27cbe145092999fe0074738732a",
          "sha1": "97e20d89334bd679b97521cb5e24ccefdd835598",
          "md5": "052d6e76291056dea05a185e059ed6ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.4-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.4-sources.jar",
          "size": 22789,
          "sha512": "2480b77d80f99899e3b483c40922af4baa1ca077f73692a4438d69f8616857459dcf8dce892eb4e6400dd5affcd386d352d5f93b7991538eed023725631c7e38",
          "sha256": "26be3aad48e6fc2af5cc4bdcb178bb0e0c178a44a7e17cd83934e2adacb9c20d",
          "sha1": "ef67509738c755dcf8a2c7af823170b13b1b90e9",
          "md5": "f9b03d6045d24f21deab8374885d2ade"
        }
      ]
    }
  ]
}
