{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 49922,
          "sha512": "8cb699edf71138e274b25d153d0fbb537c75088648f2774f66ce423a1262c368c7ed995c970710195e13dd2064d64501a87925c70f15e6cf698527384cbc8b69",
          "sha256": "95cbac65e37f1b420012880a5836626947c0716a96b3d2a41c1ade7b622a95ad",
          "sha1": "c6ae6b7ed96ec204c08f494718425aacda837ea4",
          "md5": "454e6c7a09b087a9ad4bb4e0bbd4bb66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 49922,
          "sha512": "8cb699edf71138e274b25d153d0fbb537c75088648f2774f66ce423a1262c368c7ed995c970710195e13dd2064d64501a87925c70f15e6cf698527384cbc8b69",
          "sha256": "95cbac65e37f1b420012880a5836626947c0716a96b3d2a41c1ade7b622a95ad",
          "sha1": "c6ae6b7ed96ec204c08f494718425aacda837ea4",
          "md5": "454e6c7a09b087a9ad4bb4e0bbd4bb66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "size": 25201,
          "sha512": "33b37ae42199b356f2b81feb9889b3ca302900a2b1054eb3a706b4fdcafa778efdf812ec9d5093f2f93096b936e28f97ac5dcd36fef319f5febcfd468bc7c1a9",
          "sha256": "44412474879e9bbb7e50b4a947d9c3c130bc3561d52bd21158ac1007c4747f11",
          "sha1": "976db0e6f4b96c2799ec2e28c16e94593f2fbd83",
          "md5": "1452da394fcd6b3244f38a511c873850"
        }
      ]
    }
  ]
}
