{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 86538,
          "sha512": "c3f80330c20396effcb50598b9218bdef14d57f7da8eb5ba2d24ce4046bf15d4b5bec1b2b80ce35d7a4abe8466fdc199a441bcf5769586cf41228c1da1537075",
          "sha256": "37c43f2b75574c0f29f872f524104173ec16d3b433e8932199ef560dbc1b9df5",
          "sha1": "53bd96740af10ec10bd23a3207b62c9fa01eb8af",
          "md5": "f7316a635f35a5f28f03b2d3926af13e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 86538,
          "sha512": "c3f80330c20396effcb50598b9218bdef14d57f7da8eb5ba2d24ce4046bf15d4b5bec1b2b80ce35d7a4abe8466fdc199a441bcf5769586cf41228c1da1537075",
          "sha256": "37c43f2b75574c0f29f872f524104173ec16d3b433e8932199ef560dbc1b9df5",
          "sha1": "53bd96740af10ec10bd23a3207b62c9fa01eb8af",
          "md5": "f7316a635f35a5f28f03b2d3926af13e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "size": 22807,
          "sha512": "10a9ddb9e3eacb8c8a46af2e72096cfdd2e271f06e034cda7f47c1de650812338871fa21ae21c039b7d581788aa7cec3ec0f02dbcdc1ace11c039bc7078cac70",
          "sha256": "aa316a7ae764e99a9b2fc9f47150a419f444e5b3e14682e03f42ea834202b062",
          "sha1": "9965e6fa53f9439fad49f72e08e4a92fd4a07bf6",
          "md5": "b33507effc84ed34d92f9e44d7584d7e"
        }
      ]
    }
  ]
}
