{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 6098514,
          "sha512": "2302cc26a94381fccde9020549b49aba2984321042ddfde819f57b4cec08fbf19e3e7efd583d273fd2ceba869cb7878225dab2e7220b3d7529a593fc97b19339",
          "sha256": "aa517661ea330af14480d5f2e0827dccd784400412b17be82cf32082b00b06b3",
          "sha1": "3560aea2fd4ba02651639ff844994dca8f9a4777",
          "md5": "332dbc9b3525ed551c4bc3d86183f2e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2.jar",
          "size": 6098514,
          "sha512": "2302cc26a94381fccde9020549b49aba2984321042ddfde819f57b4cec08fbf19e3e7efd583d273fd2ceba869cb7878225dab2e7220b3d7529a593fc97b19339",
          "sha256": "aa517661ea330af14480d5f2e0827dccd784400412b17be82cf32082b00b06b3",
          "sha1": "3560aea2fd4ba02651639ff844994dca8f9a4777",
          "md5": "332dbc9b3525ed551c4bc3d86183f2e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "url": "rosetta-neoforge-0.1.1+26.1.2-sources.jar",
          "size": 6076177,
          "sha512": "1ab359fe11ad91af70606a347774ca96efc9bb83e319a9da4402bc60d290a90a58f88d8827cce1fae57ff881dc3eebfbdb6af1304fd8f67533342bc47df379e7",
          "sha256": "e9bdc0a80f34a74bc15cb0fe2b20e38665704b78b9e0f5b753a04607de8890e4",
          "sha1": "fa9c928ed73785874fc8c5e8b8a9fc910f205285",
          "md5": "b4881024c5a1ed9fe9b907cbb47c3eed"
        }
      ]
    }
  ]
}
