{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "size": 49865,
          "sha512": "5a734dedf74d1a4e5aaa526826d8f55f1b72351de2d01ce9a2320e585944116cfbd355fa4239eb2e9ab5f395f8b92b3fcdadb46ba8b26d3d7f6898150bf7f9fb",
          "sha256": "2dd1812bf68073513d7df3629c7202b1aff6b0de36c1651e2e955ac85e6e2bc0",
          "sha1": "2557ca5ac01fd2217510577d212fca22b9feeee2",
          "md5": "7950c878cd4787e427788e03fc2209fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "size": 49865,
          "sha512": "5a734dedf74d1a4e5aaa526826d8f55f1b72351de2d01ce9a2320e585944116cfbd355fa4239eb2e9ab5f395f8b92b3fcdadb46ba8b26d3d7f6898150bf7f9fb",
          "sha256": "2dd1812bf68073513d7df3629c7202b1aff6b0de36c1651e2e955ac85e6e2bc0",
          "sha1": "2557ca5ac01fd2217510577d212fca22b9feeee2",
          "md5": "7950c878cd4787e427788e03fc2209fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10-sources.jar",
          "size": 25186,
          "sha512": "6e41e81744661bc3a28a89532611eeea6b84b77163be448bea0713f0f69e2c6b2041b68ada969aeee388da08e08d25b345eaa426115951e3c1a3893843f57837",
          "sha256": "69b512b4db9bbf6a3b961854ac4cee26aeb44cc2b91521134822c60ff4292f8a",
          "sha1": "3f40f022054c3c6b76a5c08453dba902fb1c2ce1",
          "md5": "79799de9dde034dd82189e30eefc401a"
        }
      ]
    }
  ]
}
