{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "size": 85710,
          "sha512": "196f8edfcf3d0b9bb4f7c159a4c57efcb5fbc0599192c15de2ab3a6e0586dace4700eec8e92053cca571cb0c013d661b08b82bc0d45f369ec4a3a417ddbeed08",
          "sha256": "7d37c9a76fa11cd3291ba10ae45f22ab7ab29e18d71918e873ebd08b39dab256",
          "sha1": "8dd21fe1433d0e5a5619ac6d2b941bd1a65f4e3a",
          "md5": "b0213fae114c77447903cbdc5da7d2db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10.jar",
          "size": 85710,
          "sha512": "196f8edfcf3d0b9bb4f7c159a4c57efcb5fbc0599192c15de2ab3a6e0586dace4700eec8e92053cca571cb0c013d661b08b82bc0d45f369ec4a3a417ddbeed08",
          "sha256": "7d37c9a76fa11cd3291ba10ae45f22ab7ab29e18d71918e873ebd08b39dab256",
          "sha1": "8dd21fe1433d0e5a5619ac6d2b941bd1a65f4e3a",
          "md5": "b0213fae114c77447903cbdc5da7d2db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.10-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.10-sources.jar",
          "size": 22782,
          "sha512": "21e975675958457de92bfd2f88e7ce0f3462570ff4c207dcb70856557d6a58841d465525d3a253a32a273a22430146b5076fb99dad5ca4eec949b7387eb71e1c",
          "sha256": "6ca83030a6fbfff72a7ed386696f3b154a6dee836a68fe24e26e1261e8f30e68",
          "sha1": "3592a7b5f69b825fc0887249acde651b0337e816",
          "md5": "d0be3c65bb2da3e7c3df3f3afc093646"
        }
      ]
    }
  ]
}
