{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 6099044,
          "sha512": "cc1e9ce3e7c8206131aef366af4a6ea674279d873f93c8952910a88387c85194b509cb49618757d71cc96eeac0e0ed225a418f3b93f5b300d11f455eefc675c9",
          "sha256": "28e9f44935da817d627d40f74b144223899a039e48a155808d3757f8bcbf36ed",
          "sha1": "eac0ea901de3a9eae10b10b2b70f4a008fbfbed6",
          "md5": "c362a9ec61f6919998f5169e4f5f2396"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 6099044,
          "sha512": "cc1e9ce3e7c8206131aef366af4a6ea674279d873f93c8952910a88387c85194b509cb49618757d71cc96eeac0e0ed225a418f3b93f5b300d11f455eefc675c9",
          "sha256": "28e9f44935da817d627d40f74b144223899a039e48a155808d3757f8bcbf36ed",
          "sha1": "eac0ea901de3a9eae10b10b2b70f4a008fbfbed6",
          "md5": "c362a9ec61f6919998f5169e4f5f2396"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "size": 6076503,
          "sha512": "f7525a5a92a267f8942bc1f8749f177ac353fd31c4b79419cd5304fa529f15ed546a7b09ae33fbb48a802ffcc1a1747c1c1fa5118af9ee93e4f77ba3d6c1d738",
          "sha256": "3c017934f8f243f8d44f9d61969313bcbeb075287a16ac5b516e465d67e8db04",
          "sha1": "c2c9bc05e2375084875fc6ed2c0ad7933fc2aef3",
          "md5": "1327d9243fc9445c788ee58aa2ad3bac"
        }
      ]
    }
  ]
}
