{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 79706,
          "sha512": "24c10bb81055d959cad3a212d26fbf470bcf47446c4d982d4884e7893d89655071ccd5d3a5c7704ac3a1ad16ae9b948551c8a565c684a10835c55e755cbdffe9",
          "sha256": "d78eef1210816fb01d1b2c324e90856951c38f6ef8c11bcfc6e4662ed7dd6d17",
          "sha1": "5fdcfd893953d5bc0dadaf09d476428da8579498",
          "md5": "8e898f6ff0b8417feb3d561aec57265c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 79706,
          "sha512": "24c10bb81055d959cad3a212d26fbf470bcf47446c4d982d4884e7893d89655071ccd5d3a5c7704ac3a1ad16ae9b948551c8a565c684a10835c55e755cbdffe9",
          "sha256": "d78eef1210816fb01d1b2c324e90856951c38f6ef8c11bcfc6e4662ed7dd6d17",
          "sha1": "5fdcfd893953d5bc0dadaf09d476428da8579498",
          "md5": "8e898f6ff0b8417feb3d561aec57265c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "size": 23048,
          "sha512": "5c57bd36a293b6bed530264c84f21fccf6c4a79b9cb876a6e284a997c22901651976e0e064e3743b1a11db82a760f3d9fe36a4c234142e1a0888f2b3565adc93",
          "sha256": "087e82fdecfc703c085e866014f4b562e5d2f709a4041e534116e2d1e6c9fbe7",
          "sha1": "395ae07dc464e547fc925d1e57dcb9b34b5c81a1",
          "md5": "8a121605f159a61008e5140e292ba0d1"
        }
      ]
    }
  ]
}
