{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 44699,
          "sha512": "245316537567e7875e559f59dc4a113fa2d0ab71dd09cbf89e1ebf599904574cd96841b48ee28a04e4cb95e02f38d1bf7ec973726fc757450c65fa8a4c67227f",
          "sha256": "4b72e31f1af42556d077fb22caa90da4b709a70174e7c6c994e83c4f232bb653",
          "sha1": "e0ef1f1a7a333b5a0d094ddf84d87e18b0ffdb55",
          "md5": "bef4c9008eb6a3578f43cbbbd1fb1f51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11.jar",
          "size": 44699,
          "sha512": "245316537567e7875e559f59dc4a113fa2d0ab71dd09cbf89e1ebf599904574cd96841b48ee28a04e4cb95e02f38d1bf7ec973726fc757450c65fa8a4c67227f",
          "sha256": "4b72e31f1af42556d077fb22caa90da4b709a70174e7c6c994e83c4f232bb653",
          "sha1": "e0ef1f1a7a333b5a0d094ddf84d87e18b0ffdb55",
          "md5": "bef4c9008eb6a3578f43cbbbd1fb1f51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.11-sources.jar",
          "size": 25344,
          "sha512": "87a5203d9a13861002f74211f1d5c222046a79c76e2ede0f0dbae4ecf21eb8f8b6840c84cd30fc1e3f93076115fa7986a742b17f8db159cef9a788ce7ec39e4c",
          "sha256": "efba02cdef761c0edf360e9031582dc0431291cbfa59cfbab3e3bafa34b7103c",
          "sha1": "f3d416f4083347efe5d21ece9e0c4ab6511f9659",
          "md5": "7e6fbb1d5a0740df7b904ed3cf4a213a"
        }
      ]
    }
  ]
}
