{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.jar",
          "size": 79118,
          "sha512": "310b37bd2ec65e82bfac8d6105664b2206fa09e494df6e2aaa0b758a130bea6ba9ec3022eff6140840d5bcdea8762e52d145dcdd085922718bb82903b5385ff4",
          "sha256": "1b87a02b1346cae00c92d61e95a907861f74bac85f50de65319f25db777252ee",
          "sha1": "1d0c2a98bd3ff873c683621dafdb09abe7c1d43a",
          "md5": "65f2d0cfa869a764ef5c0ea0ddddc477"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.1+26.1"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+26.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.jar",
          "size": 79118,
          "sha512": "310b37bd2ec65e82bfac8d6105664b2206fa09e494df6e2aaa0b758a130bea6ba9ec3022eff6140840d5bcdea8762e52d145dcdd085922718bb82903b5385ff4",
          "sha256": "1b87a02b1346cae00c92d61e95a907861f74bac85f50de65319f25db777252ee",
          "sha1": "1d0c2a98bd3ff873c683621dafdb09abe7c1d43a",
          "md5": "65f2d0cfa869a764ef5c0ea0ddddc477"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1-sources.jar",
          "size": 22816,
          "sha512": "d55c1901154efa52a5a74af47b39e2d0d7b9fa955967f3f8ed3ce91af42ff9e65585de4316b99d32b70d74191a859c39536b60cef6aac80f8edac25add9757e9",
          "sha256": "ca561e09e677b5cf1c780932b057059ca95bbffd03f41a5d4eb3221a713aa8b5",
          "sha1": "38baabfc1e1d51f6fdde4b5f2b457b419b3580ce",
          "md5": "86663bbc505c917b818d46cb49023bce"
        }
      ]
    }
  ]
}
