{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.jar",
          "size": 44423,
          "sha512": "773ae3f9b3b28c7e4183a84d84151aa051f520abff7638d15809fb0b11f59683765f2c95db5e8bfc3bea4e4f3aad58efb7ac95ae1c65bb9ef73330d53235dec0",
          "sha256": "a27126e9543345272146512554792079849aa33ebfa7a9ea736ba032159ee9e7",
          "sha1": "8f14db604587bd77ad9567a086359f75519403dc",
          "md5": "2448e27503608d07fe1eddf91b8504f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.1+26.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.jar",
          "size": 44423,
          "sha512": "773ae3f9b3b28c7e4183a84d84151aa051f520abff7638d15809fb0b11f59683765f2c95db5e8bfc3bea4e4f3aad58efb7ac95ae1c65bb9ef73330d53235dec0",
          "sha256": "a27126e9543345272146512554792079849aa33ebfa7a9ea736ba032159ee9e7",
          "sha1": "8f14db604587bd77ad9567a086359f75519403dc",
          "md5": "2448e27503608d07fe1eddf91b8504f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1-sources.jar",
          "size": 25203,
          "sha512": "6b9d729226e2257a6d439e100e694ac7abbb7cdeb54961e92bce3cc21384eb2e01faa37982dccf301daa2f33b103a8377d1949fea41380adeb5a2eef4a5f2fda",
          "sha256": "698300246c9e323ed9cee543fac258942fffd94d42c42427fae29b5a10dafb22",
          "sha1": "0e086353fe3c18aeb7b6a88027bf82570eefe6a8",
          "md5": "762c4a8128a10cb70da2cbd42311f8b1"
        }
      ]
    }
  ]
}
