{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4.jar",
          "size": 79709,
          "sha512": "118adce23473d996ae63e708d58a72b020a930538c9d52ebecfd67674b8025555ca06cd1ef9a4976d7d4cb6bbccf0f0605665c8a3c197da2c9a7b374690284e0",
          "sha256": "be0e15e234cf1e3230b5818c4bf36e9f81619142e2e137e58628791337a9cd7a",
          "sha1": "52aeff3a3cf6817622f0c1a4d62423f87c6dc986",
          "md5": "5f0c7dae36f777c3f5baf9a3374a397a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.4+1.21.4"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4.jar",
          "size": 79709,
          "sha512": "118adce23473d996ae63e708d58a72b020a930538c9d52ebecfd67674b8025555ca06cd1ef9a4976d7d4cb6bbccf0f0605665c8a3c197da2c9a7b374690284e0",
          "sha256": "be0e15e234cf1e3230b5818c4bf36e9f81619142e2e137e58628791337a9cd7a",
          "sha1": "52aeff3a3cf6817622f0c1a4d62423f87c6dc986",
          "md5": "5f0c7dae36f777c3f5baf9a3374a397a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4-sources.jar",
          "size": 23049,
          "sha512": "37542945db1a8eb68b5e74fe0faf754f136e33a3e9db82f553d14e98b2244e31ab3f2240ad986cfcfd679b4a27ba32f1705357c5b2181e232c03b49ad2dac801",
          "sha256": "e40eb94b058ad7470541c1b7fd343c0a68f70191a0cbccd121ab15d7f6101e6e",
          "sha1": "9622c2ec9e1523d0eb5abb9031eec07bb128a0ff",
          "md5": "26085963c7c6f092da6f17faaa51982b"
        }
      ]
    }
  ]
}
