{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4.jar",
          "size": 44918,
          "sha512": "75c51527713831d4cff994bb81097eb4f267f09dba059bfd461837aea8f79a0a805db4da1e02ccfd28f9cc0b036564090e0c93c0e712c42393935a410612a307",
          "sha256": "fc9e10e5c2f07665c84c539e46e77f9daafb59d40b077f32a602807d91135a83",
          "sha1": "85cb37829513e6507e4223ccd1356cf2842f905a",
          "md5": "200629816dadf10de077185886d49626"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.4+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4.jar",
          "size": 44918,
          "sha512": "75c51527713831d4cff994bb81097eb4f267f09dba059bfd461837aea8f79a0a805db4da1e02ccfd28f9cc0b036564090e0c93c0e712c42393935a410612a307",
          "sha256": "fc9e10e5c2f07665c84c539e46e77f9daafb59d40b077f32a602807d91135a83",
          "sha1": "85cb37829513e6507e4223ccd1356cf2842f905a",
          "md5": "200629816dadf10de077185886d49626"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.4-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.4-sources.jar",
          "size": 25378,
          "sha512": "88fe9dc7a7620d1b77556cc092bfd0b2f9b3fb3b0ec46a0c12c77a6523f9dc3a20dfab6ef2ad8792ef9a1a9c47a159dd6ef2b791c9fef8f6240f2d6f1149fc28",
          "sha256": "99c2ec8fcd4774ab670ef6f008e70519e8bc0de0aa5a5882ba01e219a043d98d",
          "sha1": "0535bce45c96ed087d7468e35f7b257255c04cf4",
          "md5": "250702824376d212f25cb4f5a1d48fc2"
        }
      ]
    }
  ]
}
