{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.0+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.0+26.1.1.jar",
          "size": 6098513,
          "sha512": "da474aa4873b7227bde1a714cc4e4c1355ea6c63d5cacd23349d390b62ee0f43868e2dd5ed68bd7791588bd30f7fc4037854f0b1a28d48c6aaf3885b0136936b",
          "sha256": "15eafd7b85e30f517e90ef7f0a0a9517f0aa904af059e71560a170cbdd70e969",
          "sha1": "be46c1e1d65f86fc6df286325eceb017531aca29",
          "md5": "0ff2c835996a6b1330bba4b8fa279fb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1.1.jar",
          "url": "rosetta-neoforge-0.1.0+26.1.1.jar",
          "size": 6098513,
          "sha512": "da474aa4873b7227bde1a714cc4e4c1355ea6c63d5cacd23349d390b62ee0f43868e2dd5ed68bd7791588bd30f7fc4037854f0b1a28d48c6aaf3885b0136936b",
          "sha256": "15eafd7b85e30f517e90ef7f0a0a9517f0aa904af059e71560a170cbdd70e969",
          "sha1": "be46c1e1d65f86fc6df286325eceb017531aca29",
          "md5": "0ff2c835996a6b1330bba4b8fa279fb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.0+26.1.1-sources.jar",
          "url": "rosetta-neoforge-0.1.0+26.1.1-sources.jar",
          "size": 6076177,
          "sha512": "1ab359fe11ad91af70606a347774ca96efc9bb83e319a9da4402bc60d290a90a58f88d8827cce1fae57ff881dc3eebfbdb6af1304fd8f67533342bc47df379e7",
          "sha256": "e9bdc0a80f34a74bc15cb0fe2b20e38665704b78b9e0f5b753a04607de8890e4",
          "sha1": "fa9c928ed73785874fc8c5e8b8a9fc910f205285",
          "md5": "b4881024c5a1ed9fe9b907cbb47c3eed"
        }
      ]
    }
  ]
}
