{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7.jar",
          "size": 78709,
          "sha512": "4b3350020b12d94982b44be7420a43e86a722d58941cfa21b68d2243150ffa2ba152816d8899b3579a8ef43ad2874026ba6494740be249f9bf77ba6b3d9fc9d4",
          "sha256": "95bba20882c2b536c57540a7657a3a5f344bafe5f61e153194bfe9373b2a02fc",
          "sha1": "4f700ac2a2bd0be4ee4365f4060b38dc888a97e4",
          "md5": "e8185c9938ce268cd8d96373ccd160d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.7"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.7"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7.jar",
          "size": 78709,
          "sha512": "4b3350020b12d94982b44be7420a43e86a722d58941cfa21b68d2243150ffa2ba152816d8899b3579a8ef43ad2874026ba6494740be249f9bf77ba6b3d9fc9d4",
          "sha256": "95bba20882c2b536c57540a7657a3a5f344bafe5f61e153194bfe9373b2a02fc",
          "sha1": "4f700ac2a2bd0be4ee4365f4060b38dc888a97e4",
          "md5": "e8185c9938ce268cd8d96373ccd160d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7-sources.jar",
          "size": 23049,
          "sha512": "0a20ed68f369dfca0c65329607c71d8dbacfcc625592f4e1fa8b9ae03c0ac79f8fa158e4b5c21b9a050a108bf7cc77f1cb8fa72f911d7ce7818451d22a59a31c",
          "sha256": "c7112072f8f13a0a8319170cafda93d22183f79e05d9db09ba5bd5c57818d25c",
          "sha1": "09d0c9a3f09fc183eecb5e4359040dc440c3cb5b",
          "md5": "2c0c51bb412dd102f11c5d9319c1afcf"
        }
      ]
    }
  ]
}
