{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7.jar",
          "size": 44406,
          "sha512": "b3c6b7b7a4a70dbc540a7d046dc7eb1d30a7770d7936690e55640138ca19918dcfb3b3ff8119d46267f92725fe67cb223e95627600d3a9346bc452306f7251e3",
          "sha256": "391dc61474e3e54a87954d524cbf21d573e93ec4e20942da06b61300330b7eb3",
          "sha1": "cac48d06f64629a847b537b446e558065297c1c0",
          "md5": "0e2cc253bbe175cbd25c7be281c94304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.7"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7.jar",
          "size": 44406,
          "sha512": "b3c6b7b7a4a70dbc540a7d046dc7eb1d30a7770d7936690e55640138ca19918dcfb3b3ff8119d46267f92725fe67cb223e95627600d3a9346bc452306f7251e3",
          "sha256": "391dc61474e3e54a87954d524cbf21d573e93ec4e20942da06b61300330b7eb3",
          "sha1": "cac48d06f64629a847b537b446e558065297c1c0",
          "md5": "0e2cc253bbe175cbd25c7be281c94304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.7-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.7-sources.jar",
          "size": 25381,
          "sha512": "ed2eb34b7dd60a8fe3e7430c22d4a2b5d4e25c7ce3ee52bbdd7988d5f05c2c1dda1ef078278e88df16270f4b8e6b0d255b2cac1fd9664f73fb1ae045a6cf6398",
          "sha256": "eefa01b7afabca3f3223f89b772eb681c3bc5bbbddc657c6f4312b6c55c4b832",
          "sha1": "8310eacf19bfb072e0fdb5c2f095f42da47408f4",
          "md5": "bc4a4eb3cb1a99e42e8e22ab8b9893db"
        }
      ]
    }
  ]
}
