{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "size": 78129,
          "sha512": "17d1d9347aba72df975e7e81c7c39c685a7ec8339b62feafd25b8059aed60a1dba5f6b05d20a053a2fd775beb60ee291f33f6a13079264ff5b8ab95c42dc0382",
          "sha256": "d8c50d0151e4d0e45c6d71880dcd54aa7ec0414e5e6efafaf59a368661e18957",
          "sha1": "e96ccf6c7ac5bbd5fe85418d43fc8f210452083b",
          "md5": "183f6dbebb2d7cbf6cf1c81a55c7773e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "size": 78129,
          "sha512": "17d1d9347aba72df975e7e81c7c39c685a7ec8339b62feafd25b8059aed60a1dba5f6b05d20a053a2fd775beb60ee291f33f6a13079264ff5b8ab95c42dc0382",
          "sha256": "d8c50d0151e4d0e45c6d71880dcd54aa7ec0414e5e6efafaf59a368661e18957",
          "sha1": "e96ccf6c7ac5bbd5fe85418d43fc8f210452083b",
          "md5": "183f6dbebb2d7cbf6cf1c81a55c7773e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3-sources.jar",
          "size": 22789,
          "sha512": "015823fe66fa0142758858f332043d1cc460b94dbda6725c734aadc2b326bd7d29e3ea89f7b1afd2fc7d96676ecb81aa1871d7049ffe117b0100f45d6d50a40e",
          "sha256": "1394f7fa563e392f66eee2b5476e3f22f3d117489fede045189bd0fab613edf7",
          "sha1": "5d04c650bf1277c564129bc19396ca8f9eb79b5e",
          "md5": "e551d6043dcc1f4694bc88396003b0e7"
        }
      ]
    }
  ]
}
