{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "size": 44556,
          "sha512": "8f98f728d8ef798a9ee97ca5b5d72031372aee6f982e5e23d7ac5386f61131a32d04d880bf11a46dfdbd5596c92ceea8be1267c40b0c5c2af3a19fee1da9e159",
          "sha256": "7c9a04b3857325006d6bc160980b36d5e9bf557205fbfa99053c4544e2bbed19",
          "sha1": "87e48861fc1fdb27e67cd0d5a7f4a7924807752e",
          "md5": "269b42666bdbe6faae6d8cc7f49a2820"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3.jar",
          "size": 44556,
          "sha512": "8f98f728d8ef798a9ee97ca5b5d72031372aee6f982e5e23d7ac5386f61131a32d04d880bf11a46dfdbd5596c92ceea8be1267c40b0c5c2af3a19fee1da9e159",
          "sha256": "7c9a04b3857325006d6bc160980b36d5e9bf557205fbfa99053c4544e2bbed19",
          "sha1": "87e48861fc1fdb27e67cd0d5a7f4a7924807752e",
          "md5": "269b42666bdbe6faae6d8cc7f49a2820"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.3-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.3-sources.jar",
          "size": 25203,
          "sha512": "7ab1f41694b577aebf9b5d78d372a2f737c433ebda57aea0e8fa8cfd3bde1995aed87ec79323303a9be016b6d8489ee63fe8dca7fb5f1bdb78464cbe2894d94a",
          "sha256": "65f956628744413e51eabc0b539dda348266ec090aca2e07e0460f02e4611ed1",
          "sha1": "fbd879ff329c8e0d26d13cb85d51e10d0c831c01",
          "md5": "d3745a234a8aeb83c1f28edb513dd77e"
        }
      ]
    }
  ]
}
