{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9.jar",
          "size": 78891,
          "sha512": "80d1914d1f868bbb6bb218a9bf0b9f4fe50f5f37fa73f33e3024c7c5624cc288a2c4efaab8fb8d36c2ed1f0f29f17b07336034987ba004fc3f3f6af554a57848",
          "sha256": "902a3871387291a5ad02262be0bc7d317e7af17012e2189ec7bfcde8c4d4b5c6",
          "sha1": "054ae020920bb5ff054266e7e75574ca68e36daf",
          "md5": "7950347c7ec6f84f776475fc7263e656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.1+1.21.9"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9.jar",
          "size": 78891,
          "sha512": "80d1914d1f868bbb6bb218a9bf0b9f4fe50f5f37fa73f33e3024c7c5624cc288a2c4efaab8fb8d36c2ed1f0f29f17b07336034987ba004fc3f3f6af554a57848",
          "sha256": "902a3871387291a5ad02262be0bc7d317e7af17012e2189ec7bfcde8c4d4b5c6",
          "sha1": "054ae020920bb5ff054266e7e75574ca68e36daf",
          "md5": "7950347c7ec6f84f776475fc7263e656"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9-sources.jar",
          "size": 23049,
          "sha512": "67caa4405ce8ae9fc521698f7cfc044c6d3c4d646a3ed13ed52d9f4e6cdf334c3538471c0cf04a1913924afec55f5c1196b7f9202e3df67aadfaafb73804a71a",
          "sha256": "cf93f8c573c2df050365a92a2eb04fb3bfa41130e6019eb20624203546a63367",
          "sha1": "7a38ef8210c1b03c09a58eb6041ff79942f55f53",
          "md5": "5189eaa5034a58e664b85565b5dd936f"
        }
      ]
    }
  ]
}
