{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9.jar",
          "size": 44564,
          "sha512": "e6abb7b28d5ca8845a27a0b357b1321901c5c2bede4c8610c0e8fc83f6a118834f1f49ca754f6608e98d31b9e15495ddfb29cac94903a47363a9ce2615ce24cc",
          "sha256": "7d4f6bfac5cdc64ca04f91f638869c133a99b77a84576f747ef6bb2f87a0b4a6",
          "sha1": "4aaa79ffd821220290886784f6757ea88101e1cb",
          "md5": "dfbc759cec1525b40781f32e68ae2168"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.1+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9.jar",
          "size": 44564,
          "sha512": "e6abb7b28d5ca8845a27a0b357b1321901c5c2bede4c8610c0e8fc83f6a118834f1f49ca754f6608e98d31b9e15495ddfb29cac94903a47363a9ce2615ce24cc",
          "sha256": "7d4f6bfac5cdc64ca04f91f638869c133a99b77a84576f747ef6bb2f87a0b4a6",
          "sha1": "4aaa79ffd821220290886784f6757ea88101e1cb",
          "md5": "dfbc759cec1525b40781f32e68ae2168"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.9-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.9-sources.jar",
          "size": 25375,
          "sha512": "90a6aa1ba5021b827109e1136adfc1f3b8fa3ce083c5c6097ca082c73260a66cc93977e82b35b23e4204e7cd5321aecde7c6e3eeeeeb36c5c3ae38f9784b6c40",
          "sha256": "afbf52def08c2b6d23fbd3158e4581a73e3cac7a33348267e49296c8cf9d0c81",
          "sha1": "1ea8ce85a8fc9f988d65ef5ad8524e66d50a3076",
          "md5": "929945decdcd733cd38e98098a328f74"
        }
      ]
    }
  ]
}
