{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.maltcore",
    "module": "maltcore-fabric",
    "version": "0.1.0+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.1.0+1.21.3.jar",
          "url": "maltcore-fabric-0.1.0+1.21.3.jar",
          "size": 4890,
          "sha512": "79370afb0e694a24520aa98fcdb8ef8648e5e2aafd2b9913cb8b102a923b60e072c2c4e42081f9bb6c3f2bc989e3a1d2a07002ad994461c6897e7d47989d817b",
          "sha256": "60268a3abd3aeea67e5b266a4039b768409cc47978efe067dcbbec8d65d89297",
          "sha1": "014258e9b3759f6838edb241cd684a6d3d931673",
          "md5": "f51f86f0ede26dfb462166ca5b830623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.1+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "maltcore-fabric-0.1.0+1.21.3.jar",
          "url": "maltcore-fabric-0.1.0+1.21.3.jar",
          "size": 4890,
          "sha512": "79370afb0e694a24520aa98fcdb8ef8648e5e2aafd2b9913cb8b102a923b60e072c2c4e42081f9bb6c3f2bc989e3a1d2a07002ad994461c6897e7d47989d817b",
          "sha256": "60268a3abd3aeea67e5b266a4039b768409cc47978efe067dcbbec8d65d89297",
          "sha1": "014258e9b3759f6838edb241cd684a6d3d931673",
          "md5": "f51f86f0ede26dfb462166ca5b830623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.1.0+1.21.3-sources.jar",
          "url": "maltcore-fabric-0.1.0+1.21.3-sources.jar",
          "size": 4234,
          "sha512": "d445d79bfa3ca5a7251cd0fd2f06908d8eb88a6aab6665b17fca50b914083f6353dd5b7ddc420e584bb208a6b2d6c50c53c78e5e81c5f24820b91537d58bd02b",
          "sha256": "35f1ed18aea211b9c968446a6e5562e8707d2fd3e868e5fad8b2a6ddc4d248ae",
          "sha1": "62875dad0db93dc0b51510ecac8b53e6ef8fe67e",
          "md5": "e9a7b5a14091932f9ff74774d8aadc18"
        }
      ]
    }
  ]
}
