{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "size": 44037,
          "sha512": "1bba96c0dc0110869f65d3ac1af4c6ba21ad8117dfe4fdb65cb979477ba8326b6d7066b8534bfe4b8bace3a11cba1cbfd0d0c5d3559e921cd97e6747dd5259b4",
          "sha256": "b722f56ea214c3036fd8063d60ea46fa06243bfbe0de39c94fede9aac547cfdb",
          "sha1": "b428a7879e6379ba436086bd09f57aaa83445192",
          "md5": "83098a034f1772263b4204ba93525ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "size": 44037,
          "sha512": "1bba96c0dc0110869f65d3ac1af4c6ba21ad8117dfe4fdb65cb979477ba8326b6d7066b8534bfe4b8bace3a11cba1cbfd0d0c5d3559e921cd97e6747dd5259b4",
          "sha256": "b722f56ea214c3036fd8063d60ea46fa06243bfbe0de39c94fede9aac547cfdb",
          "sha1": "b428a7879e6379ba436086bd09f57aaa83445192",
          "md5": "83098a034f1772263b4204ba93525ff8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1-sources.jar",
          "size": 25211,
          "sha512": "7d3f4e99c631039d013fec66fdad103992b831aa430e120e254760c13de5242fd13b68502e59d5b2f285264df9176673e383a82244275786f9ace4826319ccad",
          "sha256": "34c3320ea82ac7f2a66ffcb4cb6edc6506f332fcd16a68652a06abe4d5e35678",
          "sha1": "df0bd061426e2d2309e9f046ff97f2748d2598fa",
          "md5": "dd38ee1f22065af7bb99e53c159040b1"
        }
      ]
    }
  ]
}
