{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "size": 77837,
          "sha512": "6c600a9712d74edcd6fd52f44c29ab75816da27693ab77998c2a1c7ff88c7b214ccfc9b2f0ecbb124b7aa4d0bee706a5a03c560cce742349d25322eccb9763df",
          "sha256": "d8b53117819cbc40003fb6ac78f0c027f6f609d35e7a57c6933cd94d9010e43c",
          "sha1": "79a4171a220faa1c738bad97b0367720fc747df1",
          "md5": "ff5f2aa062f6899fb973ead6e00ddf29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1.jar",
          "size": 77837,
          "sha512": "6c600a9712d74edcd6fd52f44c29ab75816da27693ab77998c2a1c7ff88c7b214ccfc9b2f0ecbb124b7aa4d0bee706a5a03c560cce742349d25322eccb9763df",
          "sha256": "d8b53117819cbc40003fb6ac78f0c027f6f609d35e7a57c6933cd94d9010e43c",
          "sha1": "79a4171a220faa1c738bad97b0367720fc747df1",
          "md5": "ff5f2aa062f6899fb973ead6e00ddf29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.1-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.1-sources.jar",
          "size": 22789,
          "sha512": "59f0c5d082eb98d0f2c3a68b7fecc4404562512abc1a760af7a77008832c0aa884a0c20e518a2adfb17890ac6c969d72a6899907a9585f176be256cbd1e1c4fb",
          "sha256": "8fb39474e432da66e1cf9b059a5acc51e426f3ad5f69e2f1112a769ea3899bc8",
          "sha1": "397fd8b8e08d1eec7c11de4d37f2f509c7388560",
          "md5": "1b97ddfe83737730324fa61c77759f4c"
        }
      ]
    }
  ]
}
