{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "size": 49865,
          "sha512": "b96bbd5bfdaf3ad1ab15515c78155cf3e6add962966356e8dab37a6b4905706a441422374faa1b9745a43aed9a5950003ce352fa0581af79877aacc9f1d919ba",
          "sha256": "215209e635b7c803fae098766d8e09286acd7c472134044e223c1731bf89612c",
          "sha1": "ecd0e4d904c192ccb79da9001679195883599a3f",
          "md5": "08494fb01aaf5187008898cdbbcf2855"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "size": 49865,
          "sha512": "b96bbd5bfdaf3ad1ab15515c78155cf3e6add962966356e8dab37a6b4905706a441422374faa1b9745a43aed9a5950003ce352fa0581af79877aacc9f1d919ba",
          "sha256": "215209e635b7c803fae098766d8e09286acd7c472134044e223c1731bf89612c",
          "sha1": "ecd0e4d904c192ccb79da9001679195883599a3f",
          "md5": "08494fb01aaf5187008898cdbbcf2855"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9-sources.jar",
          "size": 25185,
          "sha512": "3234de73d53035a0bae13a4bd2986d9affa3084a7245e8190b5014393002e3d121cb84da929bcbd45ced62e22d5dd44242b2230d4ad766f49a0c799daa384552",
          "sha256": "d1025085d1395d52be32109843f7ec7678b867a6278e0a004ae7994e91b95092",
          "sha1": "6fd29e068eaf54f91e8eca09518c34bec8aac038",
          "md5": "ef8d18f1fdffc19219dbe9ce3583cc8f"
        }
      ]
    }
  ]
}
