{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "size": 85706,
          "sha512": "6ea4d66cc10fd5571e25e4ce77dbfc30f957d5237f5a7c50c74fcdaa3bd8a447354a79fa14f2306ee1e66fbfd6acd018a285259268685aa4b6e98d6ff1fca4fd",
          "sha256": "244141e0d4556bc9809d0c667cb0bc3d9ee08cd529ae54ec5b751375c77f39c9",
          "sha1": "a70f6dbcbd303d9670e11686ef165240b2961eeb",
          "md5": "56e2aa5618bdec9022736f417f4123d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9.jar",
          "size": 85706,
          "sha512": "6ea4d66cc10fd5571e25e4ce77dbfc30f957d5237f5a7c50c74fcdaa3bd8a447354a79fa14f2306ee1e66fbfd6acd018a285259268685aa4b6e98d6ff1fca4fd",
          "sha256": "244141e0d4556bc9809d0c667cb0bc3d9ee08cd529ae54ec5b751375c77f39c9",
          "sha1": "a70f6dbcbd303d9670e11686ef165240b2961eeb",
          "md5": "56e2aa5618bdec9022736f417f4123d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.9-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.9-sources.jar",
          "size": 22781,
          "sha512": "dafda9c4e6e650b265517bd98db799d5b9eb13d114f6edeb4b5a68bbf64c6c365720fe8772ff9af66e0724507eb15974f31b4dc1fb3ba0911adb8b2362d9ff04",
          "sha256": "bdcb497a3955f2b3e72a7397aff6cbc8a658b0354fe15c0bf5c2c016ce5ef18a",
          "sha1": "32ec01b33c19023707f72496d25587d69bc85a07",
          "md5": "14d352cfd61f44a3471ab8490f6972ca"
        }
      ]
    }
  ]
}
