{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2.jar",
          "size": 78549,
          "sha512": "5d361dd09d25d74f6d7681d75387a79d7070bcad6a283c57bf779571839585a8b0012452abdca18c48020817932f869293fe2a9fc1f27251c67b303112a683ab",
          "sha256": "9ca28a2db924d2abe059025d74120b20e8c5507b2fbcf9af3e02f1a1960f3b9e",
          "sha1": "9c25a94a9c50879d8a2ad155072a798d7a708f27",
          "md5": "440e5266eb3f5da8e38eb092d57a691f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.106.1+1.21.2"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2.jar",
          "size": 78549,
          "sha512": "5d361dd09d25d74f6d7681d75387a79d7070bcad6a283c57bf779571839585a8b0012452abdca18c48020817932f869293fe2a9fc1f27251c67b303112a683ab",
          "sha256": "9ca28a2db924d2abe059025d74120b20e8c5507b2fbcf9af3e02f1a1960f3b9e",
          "sha1": "9c25a94a9c50879d8a2ad155072a798d7a708f27",
          "md5": "440e5266eb3f5da8e38eb092d57a691f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2-sources.jar",
          "size": 23049,
          "sha512": "0c24161dc67bbcee9277ce6163df185bae283d440329be52714b44a64c977a1607a0c5025024a91f85bae49321affa11e721c9347936048e3d166b343b2623cd",
          "sha256": "1d192bdef9e3d5f3af830db1dd86a137814355d8f7444ff60a0578d4a72cba93",
          "sha1": "7c6899ac28546ffeefb44b0075db6eb32b5de3e2",
          "md5": "bdccd2424e9bedee23a97d35f2acdb62"
        }
      ]
    }
  ]
}
