{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2.jar",
          "size": 44917,
          "sha512": "6cb26c922b7e3351cfc8efa0d19d1c25db59eb107677c3b788ff6b56db9f00fdcf1980b697c985bd80f4eafdfb68589c0df4e576161fb1862d758e811d4bb289",
          "sha256": "147a160b86d42b13160178714d2e88286cb5a3f18bf48866bd0ad83cf4842976",
          "sha1": "2ad6d4c574c7c80e23edfdc1a25ae3c642492f89",
          "md5": "65aca0a560a891021b4ecfc28ffaf6e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.106.1+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2.jar",
          "size": 44917,
          "sha512": "6cb26c922b7e3351cfc8efa0d19d1c25db59eb107677c3b788ff6b56db9f00fdcf1980b697c985bd80f4eafdfb68589c0df4e576161fb1862d758e811d4bb289",
          "sha256": "147a160b86d42b13160178714d2e88286cb5a3f18bf48866bd0ad83cf4842976",
          "sha1": "2ad6d4c574c7c80e23edfdc1a25ae3c642492f89",
          "md5": "65aca0a560a891021b4ecfc28ffaf6e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.2-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.2-sources.jar",
          "size": 25374,
          "sha512": "5f8477d24a0d807097d48afaf0c0b56ee71f3dfe7fb64dcc5c25aeac9e7640aec3284a0514d7784ede4bef51c2db22b78cad9e3350c02a9830dfc6dd59a07c26",
          "sha256": "854834c63d522ff631c6729a1b50ce39419531f6abd0aff8fc4b7d285b3a2bc6",
          "sha1": "62488a88938d303bf5daeb2cda4db8eb51e61a4a",
          "md5": "468a0ece1416a22379bb64bd5f33ed99"
        }
      ]
    }
  ]
}
