{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.0+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+26.1.2.jar",
          "url": "rosetta-fabric-0.1.0+26.1.2.jar",
          "size": 6098765,
          "sha512": "b796a63c7992230a3a7291f40105a40d36256d932b083d9885ab64c89369bedb7c49ff555c26fa6bc3d1c68b3d77aa339827e8b440f6ff362b8ffb2c391608ee",
          "sha256": "d9992718f0b49d23d35cae184cdf500264216cd1a89c4a331b6918777cdee6aa",
          "sha1": "83e3b4d57d9dbaf8cdd7aaff41b9a1a39e61abbc",
          "md5": "3b0cb2ff7263123fde73dc237543f1d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.146.0+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+26.1.2.jar",
          "url": "rosetta-fabric-0.1.0+26.1.2.jar",
          "size": 6098765,
          "sha512": "b796a63c7992230a3a7291f40105a40d36256d932b083d9885ab64c89369bedb7c49ff555c26fa6bc3d1c68b3d77aa339827e8b440f6ff362b8ffb2c391608ee",
          "sha256": "d9992718f0b49d23d35cae184cdf500264216cd1a89c4a331b6918777cdee6aa",
          "sha1": "83e3b4d57d9dbaf8cdd7aaff41b9a1a39e61abbc",
          "md5": "3b0cb2ff7263123fde73dc237543f1d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+26.1.2-sources.jar",
          "url": "rosetta-fabric-0.1.0+26.1.2-sources.jar",
          "size": 6076172,
          "sha512": "73a0c29d31eddabc88a7c3621ad2ca19a5b73bd89223d5f250b8194722b02731039fcbb87f37dec44e6f4b63f32148b557badbe01d35c6fab867f2f65c1a6848",
          "sha256": "629fe49422dff6eb114df4f9375f6e4bcb519cd515cc6c7ec788bdc6736645b7",
          "sha1": "c22cc067de0f4f13c2a09663345a1056de28f749",
          "md5": "db30d12a20eb8f1435819a538868ac23"
        }
      ]
    }
  ]
}
