{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.maltcore",
    "module": "maltcore-fabric",
    "version": "0.2.0+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.1.jar",
          "url": "maltcore-fabric-0.2.0+26.1.1.jar",
          "size": 42430,
          "sha512": "590afe2789fd851fe89c26eedb728c3f5bb3918bc73fa5d6936310bc612220017096fede5ece1daeb4647abc7ef58a020ee0371ff73d923d4663a4bc17032895",
          "sha256": "ccd63144c039d94a8e73be4f03c40466de015ada38aa9ae588c34ed0cb10fbda",
          "sha1": "fd43829b904f16a21cbfcc4947bcdc8ce5726ab0",
          "md5": "58c538d77e553c410f69771c0e98bfe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        }
      ],
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.1.jar",
          "url": "maltcore-fabric-0.2.0+26.1.1.jar",
          "size": 42430,
          "sha512": "590afe2789fd851fe89c26eedb728c3f5bb3918bc73fa5d6936310bc612220017096fede5ece1daeb4647abc7ef58a020ee0371ff73d923d4663a4bc17032895",
          "sha256": "ccd63144c039d94a8e73be4f03c40466de015ada38aa9ae588c34ed0cb10fbda",
          "sha1": "fd43829b904f16a21cbfcc4947bcdc8ce5726ab0",
          "md5": "58c538d77e553c410f69771c0e98bfe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.1-sources.jar",
          "url": "maltcore-fabric-0.2.0+26.1.1-sources.jar",
          "size": 31448,
          "sha512": "7b891fc3b7748a023ca1c84b67ad1df5e7c4fc54befcffd76ed6ba1b7bdf6840083245af80dddc98976e921f1184c1689e1c6f2e693922ccdeb051b78b06b030",
          "sha256": "f346bbf705f44c4ee84bbf9881a3332720ec16fd95bfcd80131e1f5b1a2c65f9",
          "sha1": "da88b03cf2e60fc7b9ca7aacb929a7a0fb404c6c",
          "md5": "70f70e3f172f03915d905f1e92d98a4f"
        }
      ]
    }
  ]
}
