{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "size": 44557,
          "sha512": "1cf88f18e4a6c74d5cd5ed481aafc7037b0d0399e29c83be25ee0f2c3424ce4a98027b5f8999ff66b4a7b0fc0de6c318711a9867f24a14ae19fbc7cbde9ae0cb",
          "sha256": "94beb6fe762c1830043c6e7087ea1b9451a19c511a9d31c41c13ec6e1a59929f",
          "sha1": "5e836059fd58037f14b5f16657bb86d256fb2574",
          "md5": "ed36a69b72302cae911a30ab79e9e82a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "size": 44557,
          "sha512": "1cf88f18e4a6c74d5cd5ed481aafc7037b0d0399e29c83be25ee0f2c3424ce4a98027b5f8999ff66b4a7b0fc0de6c318711a9867f24a14ae19fbc7cbde9ae0cb",
          "sha256": "94beb6fe762c1830043c6e7087ea1b9451a19c511a9d31c41c13ec6e1a59929f",
          "sha1": "5e836059fd58037f14b5f16657bb86d256fb2574",
          "md5": "ed36a69b72302cae911a30ab79e9e82a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5-sources.jar",
          "size": 25203,
          "sha512": "b2d9f8e8631c1341abf2e9c9da83fbe2ab9c6565af0888fa04933a889b79b9d4fa4122ba4bbd306b5fc1bcf8831c99eb28b53793fca18d081ff4cf09cc78b971",
          "sha256": "e0fd9ebeb0ba6ceef44ee7384c4246018aaa5090ae2c2b5642003a63cadd5eaa",
          "sha1": "7ee6cec3a8626311e734b344ccbbb6d463ca291c",
          "md5": "0826be62779701e689459256697a202a"
        }
      ]
    }
  ]
}
