{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "size": 78049,
          "sha512": "511c074cb5663bfb1e41b79022ca2ac055e4d5901a2cb131582c46537eeb5fc6c8813523b524c7aab668bf87e34a1f83399fb2542033793dfe24b706c13bf102",
          "sha256": "29809a559da8dc79e45c45fb20e92c4eafbda53d6b1a9d0d19fbb775bc4f4b58",
          "sha1": "abe622c6eb31693d44fdfa74e897bf7ee0716eff",
          "md5": "bc9e9fc0e361946e9296aaf1e745bfc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5.jar",
          "size": 78049,
          "sha512": "511c074cb5663bfb1e41b79022ca2ac055e4d5901a2cb131582c46537eeb5fc6c8813523b524c7aab668bf87e34a1f83399fb2542033793dfe24b706c13bf102",
          "sha256": "29809a559da8dc79e45c45fb20e92c4eafbda53d6b1a9d0d19fbb775bc4f4b58",
          "sha1": "abe622c6eb31693d44fdfa74e897bf7ee0716eff",
          "md5": "bc9e9fc0e361946e9296aaf1e745bfc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.5-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.5-sources.jar",
          "size": 22789,
          "sha512": "eb3df0bba60469aab29732176d854f51acafeed217579eb31f5743e98bb8e15d6618319a99083a0bdc67fe1a897524f3c552e3296ef9a1a138fce6f9c3f443a2",
          "sha256": "de3142e63483a80769d71da80f1b5ba77fb99958aa1dc455ec9f220ca2e7a06e",
          "sha1": "37cfe8cd4bfda3482569414c7b00160729e241f0",
          "md5": "37e922bf3125b472f0bf58a0097a2e3d"
        }
      ]
    }
  ]
}
