{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1.jar",
          "size": 78252,
          "sha512": "7abfe5dc15333b59ca94333a2e0e04861170d4f15f88855303a8ab6da5442c36adbb6d6b8b542ffda9b7b5c292888abb6813c23bdd31ae9ec0fca6959bbe17b2",
          "sha256": "9a03d31dc7431f03a0009beaa1a1f30553fe4af0e39aa8374edd4ed9a745afbf",
          "sha1": "5d35764da1a2db63d61aa6c3f0b75d8f8a2e528a",
          "md5": "cf76ef2de6598802be1112be44768fa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.4+1.21.1"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1.jar",
          "size": 78252,
          "sha512": "7abfe5dc15333b59ca94333a2e0e04861170d4f15f88855303a8ab6da5442c36adbb6d6b8b542ffda9b7b5c292888abb6813c23bdd31ae9ec0fca6959bbe17b2",
          "sha256": "9a03d31dc7431f03a0009beaa1a1f30553fe4af0e39aa8374edd4ed9a745afbf",
          "sha1": "5d35764da1a2db63d61aa6c3f0b75d8f8a2e528a",
          "md5": "cf76ef2de6598802be1112be44768fa0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1-sources.jar",
          "size": 23049,
          "sha512": "40ebbd4f7785f25687af43e486d57ebe1723efc7b4af1bbd3566a411db9c8325a2d879a020587bc67b8ac3d0a5719235538cc3eecce337bffaf34806d4c78126",
          "sha256": "2ea3813399d988bdc8387077fff94d0ac8a7115c3c4e778c3b7ea3a5a6009f40",
          "sha1": "94f199a00a53b328a0c0203b2681fa32632cb0e1",
          "md5": "8c5ffaedac8f4ee9d82526f742a18597"
        }
      ]
    }
  ]
}
