{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1.jar",
          "size": 44418,
          "sha512": "25b98196aa73d2bd5212fbb47a8e4d00a47d8882ee05c53b71661f526d8768c38b8ce2cca2ae986cde3fb60532d44545fc240427896528507ecd31791a3acb56",
          "sha256": "5b1dfe94bc2a3ca68382d51092d9af33dae2cdbf3047594314bea501a633b0c7",
          "sha1": "a3e45a9232212616d690fe79fd9aa34544a36716",
          "md5": "572bab9a859e07221d5bb5fd29846115"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.4+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1.jar",
          "size": 44418,
          "sha512": "25b98196aa73d2bd5212fbb47a8e4d00a47d8882ee05c53b71661f526d8768c38b8ce2cca2ae986cde3fb60532d44545fc240427896528507ecd31791a3acb56",
          "sha256": "5b1dfe94bc2a3ca68382d51092d9af33dae2cdbf3047594314bea501a633b0c7",
          "sha1": "a3e45a9232212616d690fe79fd9aa34544a36716",
          "md5": "572bab9a859e07221d5bb5fd29846115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.1-sources.jar",
          "size": 25388,
          "sha512": "e67145f47d2c89e847d4bec65fa5652e2a74fdd90dd6c845b5fc4a34a91173aa03fdb73fbfbad3127fac88886f4c5c67735add2bf954c34adccdb3e250e03786",
          "sha256": "61985e9e4ec5862a6c90d1456f243ea1a3f3dcb35fd4c773050ad22d75a26f57",
          "sha1": "15c0906acd307e0a34041cc852796a03521091bd",
          "md5": "9bee9209b676cd984c3c879178142bfe"
        }
      ]
    }
  ]
}
