{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.2.jar",
          "url": "rosetta-fabric-0.1.1+26.2.jar",
          "size": 79346,
          "sha512": "b6c2763d59cffff186a0018db609904bddeb79dcc303850296f6ade8e6f802fa76e589823102179cb0f932f94b4b2327e2c013cef21552e85b7a2edebc09d049",
          "sha256": "21390a079a229081fda15cca8a6d32e212ea33a47807ad6bde1a026e63751c27",
          "sha1": "12af48e48a852162a3596f4e8700d7b4babd538d",
          "md5": "1bc9abbb1649eb31aa8b3b02c0a927a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.152.2+26.2"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.2.jar",
          "url": "rosetta-fabric-0.1.1+26.2.jar",
          "size": 79346,
          "sha512": "b6c2763d59cffff186a0018db609904bddeb79dcc303850296f6ade8e6f802fa76e589823102179cb0f932f94b4b2327e2c013cef21552e85b7a2edebc09d049",
          "sha256": "21390a079a229081fda15cca8a6d32e212ea33a47807ad6bde1a026e63751c27",
          "sha1": "12af48e48a852162a3596f4e8700d7b4babd538d",
          "md5": "1bc9abbb1649eb31aa8b3b02c0a927a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.2-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.2-sources.jar",
          "size": 22845,
          "sha512": "ca385bb93e12c7e94592a907459739bbc75c217b1d9cc1819ac61f8440c50bbbdd19aa0960596da1a4b47ab0eb9a490efd638a1bd4cc21dd9ccab18d370d5126",
          "sha256": "ed47e8e0bcf5e6499f1518f9d01a343932c24b5cdf8577619a2395f247687fe9",
          "sha1": "c92ccaeb63fa72546f1def2106ad84bc9b924522",
          "md5": "2c15745224c91df391d099855b10a3d6"
        }
      ]
    }
  ]
}
