{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "size": 78289,
          "sha512": "1011dbba8ba1d85f64e49b89ccf5397d97cde5190b5082a9dd9dbd9e594b582e0bc3c7ff8b59a0ddff56f9435fedcd260c9b48d481e4667b43cad20fdc5ed906",
          "sha256": "aecb2ed6dd0b0a0d2a8c96a11308d2c06a5a9776d809f2520cf62f9b57b00932",
          "sha1": "39be36489b8997c6fbc8a044f10b126a1e1152d5",
          "md5": "1942037c5bfbcfa3a1cab3c5b1daf413"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.7"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "size": 78289,
          "sha512": "1011dbba8ba1d85f64e49b89ccf5397d97cde5190b5082a9dd9dbd9e594b582e0bc3c7ff8b59a0ddff56f9435fedcd260c9b48d481e4667b43cad20fdc5ed906",
          "sha256": "aecb2ed6dd0b0a0d2a8c96a11308d2c06a5a9776d809f2520cf62f9b57b00932",
          "sha1": "39be36489b8997c6fbc8a044f10b126a1e1152d5",
          "md5": "1942037c5bfbcfa3a1cab3c5b1daf413"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7-sources.jar",
          "size": 22789,
          "sha512": "b097b6548d3ea920886c468833446e57a113ea5c76334a6f8dc82626f0d9c57635a464c17d5ad85247a7b73622e7f9538a8012037967bab101e0fe9700585858",
          "sha256": "7b8cec4b15cb6d1d745f23c4227150e8e783566c2dfe635083d3e2cd467302fc",
          "sha1": "e743b162eb35cc992b7c66df797f929cc3f757fa",
          "md5": "8cdcc78fb45cb6921b2db6ddba723236"
        }
      ]
    }
  ]
}
