{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "size": 44003,
          "sha512": "28097d0fa19aa5734086138c1f6b53f5c39e31114b3f52227e489574c794b20e45cb72bfb02f24e0a48e81274020f2c7c647b776294cfed0365d2bb41404cd34",
          "sha256": "b69b969af7f4b4ac373876245c7a775fc844c410888fa634a379b249d106debd",
          "sha1": "9b6746c8a5cce027afdc3d7f993335362afebefc",
          "md5": "7c06eb9815eefe6d927bcc8c29e3678f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7.jar",
          "size": 44003,
          "sha512": "28097d0fa19aa5734086138c1f6b53f5c39e31114b3f52227e489574c794b20e45cb72bfb02f24e0a48e81274020f2c7c647b776294cfed0365d2bb41404cd34",
          "sha256": "b69b969af7f4b4ac373876245c7a775fc844c410888fa634a379b249d106debd",
          "sha1": "9b6746c8a5cce027afdc3d7f993335362afebefc",
          "md5": "7c06eb9815eefe6d927bcc8c29e3678f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.7-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.7-sources.jar",
          "size": 25199,
          "sha512": "9cb8e50815dbff1fdd7b3dcb9819cf8d727c8923919bf556cf66dbbba81d1b479610869179b240f4d2389f2f9dfaf759dfac50186641882e3c6c4a6f7b1b3312",
          "sha256": "cd1c39f93c554d18d6248850bdfadb0ea18033518779edf0948ec0a7c22bea8f",
          "sha1": "22340e058ebb9aad9575d5e0abd6818a9e2af786",
          "md5": "cbdcbfac804a15ac7ec903adf07d5c1d"
        }
      ]
    }
  ]
}
