{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1.jar",
          "size": 79123,
          "sha512": "7404d54486c7e4af4486685c785650394ab919cb9ce48d10d6663c9963d7817b0c2fc37cbb8b78b7b9e3ad68303a68c9238af79a359c03e92d8528bb7263e02e",
          "sha256": "4341fc83784fdeebdf1109f0269cb83c88cc4135e4271880306e4aec9010eed5",
          "sha1": "f0a4837868d542cab8910b10c136e09443021c7c",
          "md5": "5a59e1e670d0d50e41cbee55c4e2c3b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+26.1.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1.jar",
          "size": 79123,
          "sha512": "7404d54486c7e4af4486685c785650394ab919cb9ce48d10d6663c9963d7817b0c2fc37cbb8b78b7b9e3ad68303a68c9238af79a359c03e92d8528bb7263e02e",
          "sha256": "4341fc83784fdeebdf1109f0269cb83c88cc4135e4271880306e4aec9010eed5",
          "sha1": "f0a4837868d542cab8910b10c136e09443021c7c",
          "md5": "5a59e1e670d0d50e41cbee55c4e2c3b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1-sources.jar",
          "size": 22817,
          "sha512": "0b01d09d006faeef263ec4e05533b21eed554ee1856c35fece9f65806a1005ecbcadde6a2183bd78be0a2a7e4788823a070efb2a17c5bb7c216715f1e9f21130",
          "sha256": "eb14ec660a8764f2f9a0c9f06c059b4bf9c5c10fb8e88fe50ec1e85dca162418",
          "sha1": "cb5d63c85f9d6c6d3b3fcb871f7ca5f948e59c4a",
          "md5": "386387bf13a50c572295375ae321b095"
        }
      ]
    }
  ]
}
