{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1.jar",
          "size": 44426,
          "sha512": "1362b34c7c3d3aec46afbeca7bfa2a92300c20949e935f627a21eb422429ea9121f039b0da198d4029dbfd22ca73b8677f34ba74a07091e404048bc5dfb5220a",
          "sha256": "ee78c38469ad3bed00fdfd7cf60551a5f26b99a6dc2468a3664f61237cc5d3ad",
          "sha1": "6b31751078ed671daa7917c1af85509e21c9f6d7",
          "md5": "e79c7a34fff7cc82865f7fc091d41069"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1.jar",
          "size": 44426,
          "sha512": "1362b34c7c3d3aec46afbeca7bfa2a92300c20949e935f627a21eb422429ea9121f039b0da198d4029dbfd22ca73b8677f34ba74a07091e404048bc5dfb5220a",
          "sha256": "ee78c38469ad3bed00fdfd7cf60551a5f26b99a6dc2468a3664f61237cc5d3ad",
          "sha1": "6b31751078ed671daa7917c1af85509e21c9f6d7",
          "md5": "e79c7a34fff7cc82865f7fc091d41069"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+26.1.1-sources.jar",
          "url": "rosetta-fabric-0.1.1+26.1.1-sources.jar",
          "size": 25204,
          "sha512": "3b9109cdff2a421cfca1126c822410547f1dc43b65a34b07b6d4873719a6d88a0a145f916e7315dd7a5adef5dbd287b7ff2bee4843f65278e7ed75532d4479d1",
          "sha256": "7eeb1aa5054f5dc7d3ddcd6a68ff42e8de1a5f61b24d1801ffd460379223f514",
          "sha1": "687bb49e5e5e85572cf68a7b8a911cd6d1cfb05a",
          "md5": "d21663df37d2e01b87edf15d3da58e4d"
        }
      ]
    }
  ]
}
