{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "size": 86409,
          "sha512": "e575a1c2ad5e0fe0fc4d0c2e490f0327ae662c433ed053d71c21eacb83d3be6f1904bf155b513f612ed7c9ce5b0df5cd4af8d6087d3341b2551ded2aee74d300",
          "sha256": "474cc76e6cf9c062764670168b49c8df020feaec79701e648cba158e734595e2",
          "sha1": "a1f8a6825e82b9d6b614ecd8c5a8461564de2319",
          "md5": "60a607e4fb3f01b01c862140a8f250f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "size": 86409,
          "sha512": "e575a1c2ad5e0fe0fc4d0c2e490f0327ae662c433ed053d71c21eacb83d3be6f1904bf155b513f612ed7c9ce5b0df5cd4af8d6087d3341b2551ded2aee74d300",
          "sha256": "474cc76e6cf9c062764670168b49c8df020feaec79701e648cba158e734595e2",
          "sha1": "a1f8a6825e82b9d6b614ecd8c5a8461564de2319",
          "md5": "60a607e4fb3f01b01c862140a8f250f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11-sources.jar",
          "size": 22746,
          "sha512": "8f602f080bf95a6727921b4b7d54429b6f06c4bdd595502588a98016fe67c30b08e7b723836b8c1b630aafd9e3768123872c486593d09e545390e75eed256c4f",
          "sha256": "b6b76344a9a14fd840ad1737be560fab16a80888e36ea8bcd3891fe25011447c",
          "sha1": "e84527cb6aafd4aa6a63f0d60a0110c7da6edb1f",
          "md5": "687ad037c97961d2d56f5f3e20a0197e"
        }
      ]
    }
  ]
}
