{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "size": 49863,
          "sha512": "81c381faadfe51c2ef55c339424421185f92a69d90e1742f389e1c6c614c460335333b1d51e59342f485982c54e0ae4f1142ebe3eac81f24ff03e5fb8bcaf1cd",
          "sha256": "15fda46107e47dd0bc36d7f77b9f20d145d66d319668ccb036e06447edc82a2b",
          "sha1": "ff688c051134a34c0f670dd8a7e4a267a8238927",
          "md5": "81a271014b57cc9ae9b944262b1763b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11.jar",
          "size": 49863,
          "sha512": "81c381faadfe51c2ef55c339424421185f92a69d90e1742f389e1c6c614c460335333b1d51e59342f485982c54e0ae4f1142ebe3eac81f24ff03e5fb8bcaf1cd",
          "sha256": "15fda46107e47dd0bc36d7f77b9f20d145d66d319668ccb036e06447edc82a2b",
          "sha1": "ff688c051134a34c0f670dd8a7e4a267a8238927",
          "md5": "81a271014b57cc9ae9b944262b1763b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.11-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.11-sources.jar",
          "size": 25138,
          "sha512": "7ad8992c9b5b1cb3751679de04aa62590b735fbd8a00807b0c92a3e22365992283ff1f54acacb46d7089086e3e5fcc186e08e2351be8520660b8ddb641273aac",
          "sha256": "dd2814daa6af23172bb42d0e8d3dd5568bc3826d77a990cd55dc209120a5c239",
          "sha1": "d54206bea98dd342f1ecee78aab8cc24d3caf63d",
          "md5": "38266adec0a03d7b8e8f1fbe0ec375e2"
        }
      ]
    }
  ]
}
