{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.maltcore",
    "module": "maltcore-fabric",
    "version": "0.2.0+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.2.jar",
          "url": "maltcore-fabric-0.2.0+26.1.2.jar",
          "size": 42430,
          "sha512": "b7c8be1bd707b719940f8b2cca704ea66a53ffd66c5be37c3935a176a4c81e246b8933ed73c20a8604b5ebb193977b55da42dbe8cd43aed352bfaf3dbe89c8bf",
          "sha256": "998bef85f35bfe5fccbb253122d003dac193940a7092b17b449fd047273a25b7",
          "sha1": "828ae9642f3378ac932d230b7f63086e2262e0a8",
          "md5": "62946a0d75cf08877a1750d8942c9534"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.146.0+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        }
      ],
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.2.jar",
          "url": "maltcore-fabric-0.2.0+26.1.2.jar",
          "size": 42430,
          "sha512": "b7c8be1bd707b719940f8b2cca704ea66a53ffd66c5be37c3935a176a4c81e246b8933ed73c20a8604b5ebb193977b55da42dbe8cd43aed352bfaf3dbe89c8bf",
          "sha256": "998bef85f35bfe5fccbb253122d003dac193940a7092b17b449fd047273a25b7",
          "sha1": "828ae9642f3378ac932d230b7f63086e2262e0a8",
          "md5": "62946a0d75cf08877a1750d8942c9534"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maltcore-fabric-0.2.0+26.1.2-sources.jar",
          "url": "maltcore-fabric-0.2.0+26.1.2-sources.jar",
          "size": 31449,
          "sha512": "8872f7fb27494758496fec1b485abdbb7830ad7fd5fda1b7b4aa537881da113df69f1baae59cc2825897300679c621a0170ed7425d8d0fbda6adcac397c05318",
          "sha256": "76ace2dd98c0c0d20363a0e4c8a15317d4f4c6591424f282f64299ce7fd152c3",
          "sha1": "84956bda93fe0a5e668be2762211b2f1cb1fe8b1",
          "md5": "e45e87a64e17a9c6cf8b1fee5b3c2b8d"
        }
      ]
    }
  ]
}
