{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.0+1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.3.jar",
          "url": "rosetta-fabric-0.1.0+1.21.3.jar",
          "size": 6099262,
          "sha512": "ce2d78f76f8605417b9aba55903b7dee66b1bda04eaae143e952eb549f5384a2d04f7aa2804cfc70e22797d86c7216bbe892ccf9d6bbffe14295959a26b5b6d2",
          "sha256": "b407c6937763ff95ceac437f777814e267e0cbd285b789e305c0de9f2015242c",
          "sha1": "a6164777df5926e7d539bc4d093f832d43273ca7",
          "md5": "c49f467e749865f9a6124dbde267daf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.1+1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.3.jar",
          "url": "rosetta-fabric-0.1.0+1.21.3.jar",
          "size": 6099262,
          "sha512": "ce2d78f76f8605417b9aba55903b7dee66b1bda04eaae143e952eb549f5384a2d04f7aa2804cfc70e22797d86c7216bbe892ccf9d6bbffe14295959a26b5b6d2",
          "sha256": "b407c6937763ff95ceac437f777814e267e0cbd285b789e305c0de9f2015242c",
          "sha1": "a6164777df5926e7d539bc4d093f832d43273ca7",
          "md5": "c49f467e749865f9a6124dbde267daf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.0+1.21.3-sources.jar",
          "url": "rosetta-fabric-0.1.0+1.21.3-sources.jar",
          "size": 6076532,
          "sha512": "7f69ae6d68b721c59f8e79c266c3414ee1bda72e531443c18dacd711e05e6dab6775adb97cda8664ae9663cf521a866470e748d332863d49d244e765c2169220",
          "sha256": "019a59b9f025d201416ec185a923b5e1489e9a79eab93b9100acf69dd74407d0",
          "sha1": "5b5491727650bc4f451856bc93843e91bb12a91c",
          "md5": "11f5d81ffb3cb295de526e948905e2f7"
        }
      ]
    }
  ]
}
