{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "size": 78286,
          "sha512": "b006aadd4110b6a158a56816aecc591193eba1290ea8b77a5172ec0af453d17a83d1a50b114fbe00d4b96fb5d65fb0a6ee98da62fd6710a3926aa31852ffa953",
          "sha256": "55101247fdddbd12c4b9ea7b6671d56bb16b80205b07909997711b22689dff77",
          "sha1": "939f2ba3e04af17b090a997815877b704d51cc08",
          "md5": "32b5eeee7ef2bf8cbc81c110b3bd431a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-neoforge",
          "version": {
            "requires": "0.2.0+1.21.6"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "size": 78286,
          "sha512": "b006aadd4110b6a158a56816aecc591193eba1290ea8b77a5172ec0af453d17a83d1a50b114fbe00d4b96fb5d65fb0a6ee98da62fd6710a3926aa31852ffa953",
          "sha256": "55101247fdddbd12c4b9ea7b6671d56bb16b80205b07909997711b22689dff77",
          "sha1": "939f2ba3e04af17b090a997815877b704d51cc08",
          "md5": "32b5eeee7ef2bf8cbc81c110b3bd431a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6-sources.jar",
          "size": 22789,
          "sha512": "06207a165d5c5127a559382600281dfa4ba1151933a4cb3d297b8c81a3f300f529c902e18b7c544ced2f4cfc7d958b0bc22c5e0afcf0f80ad93b9d06416cb5b8",
          "sha256": "4d7d0bf942befbfe3ab318869c58b248f2b2b4aba7fe030c195652b629e06013",
          "sha1": "5dc1fd96d6011ee94cb2dfc512e87ed21b9683b0",
          "md5": "6f4b6788951be638ac123e39197b3e9b"
        }
      ]
    }
  ]
}
