{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-neoforge",
    "version": "0.1.1+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "size": 44003,
          "sha512": "ec021478160a7db7af89ca77bd5af892a58a8e3cf9a2edce5b519c05c0cd676c3f71e4a19f7448fc351baccefc7d667b13c0cb86783665bf28ea4ddf23eb615e",
          "sha256": "587b610cb1cf6adf26518722958eaf3ff5f4e4c406397a17cc55c7832a9edcc5",
          "sha1": "6c60932170aab58cff204929a28e4920cc823fe4",
          "md5": "e07261ee3155d3d4c16cfe5e1539f296"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6.jar",
          "size": 44003,
          "sha512": "ec021478160a7db7af89ca77bd5af892a58a8e3cf9a2edce5b519c05c0cd676c3f71e4a19f7448fc351baccefc7d667b13c0cb86783665bf28ea4ddf23eb615e",
          "sha256": "587b610cb1cf6adf26518722958eaf3ff5f4e4c406397a17cc55c7832a9edcc5",
          "sha1": "6c60932170aab58cff204929a28e4920cc823fe4",
          "md5": "e07261ee3155d3d4c16cfe5e1539f296"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-neoforge-0.1.1+1.21.6-sources.jar",
          "url": "rosetta-neoforge-0.1.1+1.21.6-sources.jar",
          "size": 25199,
          "sha512": "376388d47cf2828467b22de01786118879b7c910ac0e9d4c17a35b403caba6527cab888dfa8e9a371fff0d9351334992393b0ff7b230c5804e98b8197229cb0a",
          "sha256": "514eb86ada9814a960c8faed8e79aa88656be2b58100f747e0d03843da3462c8",
          "sha1": "b42f6d94acd8338e347eb8e4dc01705b05313a03",
          "md5": "cf107f90dba0c84dfc1e1addff2cd440"
        }
      ]
    }
  ]
}
