{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6.jar",
          "size": 78712,
          "sha512": "09ec2c8ce2fe3478d1055f150988d0b9c045bf02d6e9779d8c2a3d16dc183b856dcb3a1fb467e78230af48679be51b3df0f1728f5d6864f260f97771ef8e3460",
          "sha256": "d5272c4617cf984d9dadaf42aad7cf0679026946f9019528839586044508ffd6",
          "sha1": "191e48b1b45a3fe7dbc382077d29d73ca4fd8052",
          "md5": "e2f8e46194f149dae408a21dcf88777c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.128.2+1.21.6"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.6"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6.jar",
          "size": 78712,
          "sha512": "09ec2c8ce2fe3478d1055f150988d0b9c045bf02d6e9779d8c2a3d16dc183b856dcb3a1fb467e78230af48679be51b3df0f1728f5d6864f260f97771ef8e3460",
          "sha256": "d5272c4617cf984d9dadaf42aad7cf0679026946f9019528839586044508ffd6",
          "sha1": "191e48b1b45a3fe7dbc382077d29d73ca4fd8052",
          "md5": "e2f8e46194f149dae408a21dcf88777c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6-sources.jar",
          "size": 23050,
          "sha512": "f85a3c9e9877ec1aa4ca873231fc62e74ba4c93bbf720ffcf1f3c0c9f5131e60e55164997f5242188d1d2b6aa64378df75402fc32f3fd123db1dcba292495991",
          "sha256": "275c7ecee29a2e49b61447a4ec2eb47034f11da48acccd7aac8d963bf6a8dc04",
          "sha1": "e2a433619c8206b37021e96709a6b3bd7ffc70e2",
          "md5": "77458953c273f99dc8eacda2d7d96988"
        }
      ]
    }
  ]
}
