{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6.jar",
          "size": 44406,
          "sha512": "fa0dea2ca31f7ea0dcd8208b8a0034d4bedec1051880993bca0f4afe89877de6b55e6984a1de37a3345921f265a1ead1e893e8d77089fcdd3899d42673d95f5a",
          "sha256": "f1046b16ebf7efc0e47000db126a372524ad6d68caa21fd00ee54cb4546d3850",
          "sha1": "7cd612ddbbb486f0c2b545b4f4bd0476692cc87d",
          "md5": "4c52e1a3a6e708c29c49f97871316ff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.128.2+1.21.6"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6.jar",
          "size": 44406,
          "sha512": "fa0dea2ca31f7ea0dcd8208b8a0034d4bedec1051880993bca0f4afe89877de6b55e6984a1de37a3345921f265a1ead1e893e8d77089fcdd3899d42673d95f5a",
          "sha256": "f1046b16ebf7efc0e47000db126a372524ad6d68caa21fd00ee54cb4546d3850",
          "sha1": "7cd612ddbbb486f0c2b545b4f4bd0476692cc87d",
          "md5": "4c52e1a3a6e708c29c49f97871316ff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.6-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.6-sources.jar",
          "size": 25381,
          "sha512": "e2261651e425dc2c7a635e2d4ece2b523a867cdb0c6d37170acf071bec5eddb4647e28e1a5bd46854ea0207a053fb8d7342e01a32a40ee4e6133bc16b7848e09",
          "sha256": "14352f6e2de710b82851abc6a5026266f3c1922a0e31e496025b5531c04ea12f",
          "sha1": "a10b44642f6816c1b4eb2cf22bf7e9defaf19fd3",
          "md5": "29b4671971cf18583d30d24bd5cdefad"
        }
      ]
    }
  ]
}
