{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10.jar",
          "size": 44565,
          "sha512": "a61962f7f49db2b0bc9a6a19c56edc3fda74493535ed424a20ad49275b07dc630862be20ecb2b67bc45561e08d18037c77268e723abb4c9bed0c5685e05cb5a5",
          "sha256": "b9fa451712ed1752e0550056bf32873c74a9f768d95c1603afc11c633bae9621",
          "sha1": "735bce45752e2a7d09068fc5f37b5d485d6ac205",
          "md5": "08fd4191801a9ea995f95c5cc1178506"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.4+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10.jar",
          "size": 44565,
          "sha512": "a61962f7f49db2b0bc9a6a19c56edc3fda74493535ed424a20ad49275b07dc630862be20ecb2b67bc45561e08d18037c77268e723abb4c9bed0c5685e05cb5a5",
          "sha256": "b9fa451712ed1752e0550056bf32873c74a9f768d95c1603afc11c633bae9621",
          "sha1": "735bce45752e2a7d09068fc5f37b5d485d6ac205",
          "md5": "08fd4191801a9ea995f95c5cc1178506"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10-sources.jar",
          "size": 25375,
          "sha512": "19df08501b1aa1b2d2878a52ed8282c46bfcec723b45b1fd1c60be81bafb03b260e9fbdd0ee6d740ddd4aa19faba97da34ae7fc01b36edb4969ea2d17483b7c0",
          "sha256": "28629fbd9ed8c72eb7456f39c57f6f94b8d10f43762edae907b9a0b7b0e894b2",
          "sha1": "345dc1dbae92d7627e17fe4f10f1e29435358443",
          "md5": "83755a7bad4d7031726428b26d568495"
        }
      ]
    }
  ]
}
