{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.malteas.rosetta",
    "module": "rosetta-fabric",
    "version": "0.1.1+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10.jar",
          "size": 78895,
          "sha512": "1e1121a0c7083b53a3018ae7124fb6893490103eed289dc6e7733f170479d63371d3b8974f639faf5e73f4a2d8b11aed7da475c829f480fbd38cfef84c43ebf5",
          "sha256": "9d508db81c6f20e0534826ff1e61e142c109fe21a0ae09c2bdee60ef21a909f8",
          "sha1": "5e723f7dd0a0debb5f4daf85e75d6166a18d6bb3",
          "md5": "a7fcef93548ba73b8226788b3ce1a294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.4+1.21.10"
          }
        },
        {
          "group": "io.github.malteas.maltcore",
          "module": "maltcore-fabric",
          "version": {
            "requires": "0.2.0+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10.jar",
          "size": 78895,
          "sha512": "1e1121a0c7083b53a3018ae7124fb6893490103eed289dc6e7733f170479d63371d3b8974f639faf5e73f4a2d8b11aed7da475c829f480fbd38cfef84c43ebf5",
          "sha256": "9d508db81c6f20e0534826ff1e61e142c109fe21a0ae09c2bdee60ef21a909f8",
          "sha1": "5e723f7dd0a0debb5f4daf85e75d6166a18d6bb3",
          "md5": "a7fcef93548ba73b8226788b3ce1a294"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rosetta-fabric-0.1.1+1.21.10-sources.jar",
          "url": "rosetta-fabric-0.1.1+1.21.10-sources.jar",
          "size": 23050,
          "sha512": "e2d61d62cda9553ca5ae74de2bfe755efffa7c01a431ca01990c26c7b2adb81eb6ec1ad7153b37251f5e58b0bc4dcfce8d5da5f0d581b6c23b311e5b1896f96e",
          "sha256": "7459b39060a309bb1a18a26ebe21f94a1a3bdab17d3b7df3544a56aecf03520a",
          "sha1": "d23900caa9417d63b921cef608782d11eb7f2163",
          "md5": "aaab15fca32264dc0dbe0ea7ed00d075"
        }
      ]
    }
  ]
}
